# Prepare data for Batch Correction

In [105]:
import pandas as pd
import numpy as np

In [106]:
clinical_gex = pd.read_csv('../dataset/created/clinical_gex.csv', index_col='Unnamed: 0', low_memory=False)
clinical_gex

,patientID,sex,age,AJCC_stage,M_stage,LDH,immunotherapy_treatment,pre_MAPKi_treatment,source,pfs_label,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,YR_3053,male,26,IV,M1B,elevated,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,YR_3708,female,58,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,YR_3705,male,45,IV,M1A,normal,no,no,Yan et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YR_1106,male,48,IIIC,NaN,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YR_1110,male,33,IV,M1C,normal,no,no,Yan et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HL_Shi-35,male,61,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,HL_Shi-37,male,65,IV,M1A,NaN,no,no,Hugo et al.,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,HL_Shi-38,male,51,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,HL_Shi-43,female,41,IV,M1C,NaN,no,no,Hugo et al.,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,HL_Shi-44,male,83,IV,M1C,NaN,no,no,Hugo et al.,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
CLINICAL_COLS = ["patientID", "sample_id", "sex", "age", "AJCC_stage", "M_stage", "LDH",
                "immunotherapy_treatment", "pre_MAPKi_treatment",
                "source", "cobimetinib", "dabrafenib", "trametinib","vemurafenib", 
                "C195W", "K601I", "MND", "R558Q", "V600E", "V600K","V600R", "pfs_label"]
GEX_COLS = [c for c in clinical_gex.columns if c not in CLINICAL_COLS]

total_col = len(CLINICAL_COLS) + len(GEX_COLS)

print(f"Clinical + GEX: {len(CLINICAL_COLS)} + {len(GEX_COLS)} = {total_col}")

Clinical + GEX: 22 + 51465 = 51487

In [108]:
GEX_COLS

['7A5',
 'A1BG',
 'A1BG-AS1',
 'A1CF',
 'A26C3',
 'A2BP1',
 'A2LD1',
 'A2M',
 'A2M-AS1',
 'A2ML1',
 'A2ML1-AS1',
 'A2MP1',
 'A3GALT2',
 'A4GALT',
 'A4GNT',
 'AA06',
 'AAA1',
 'AAAS',
 'AACS',
 'AACSL',
 'AACSP1',
 'AADAC',
 'AADACL1',
 'AADACL2',
 'AADACL2-AS1',
 'AADACL3',
 'AADACL4',
 'AADACP1',
 'AADAT',
 'AAED1',
 'AAGAB',
 'AAK1',
 'AAMDC',
 'AAMP',
 'AANAT',
 'AAR2',
 'AARD',
 'AARS',
 'AARS1',
 'AARS2',
 'AARSD1',
 'AASDH',
 'AASDHPPT',
 'AASS',
 'AATBC',
 'AATF',
 'AATK',
 'AATK-AS1',
 'ABAT',
 'ABCA1',
 'ABCA10',
 'ABCA11',
 'ABCA11P',
 'ABCA12',
 'ABCA13',
 'ABCA17P',
 'ABCA2',
 'ABCA3',
 'ABCA4',
 'ABCA5',
 'ABCA6',
 'ABCA7',
 'ABCA8',
 'ABCA9',
 'ABCB1',
 'ABCB10',
 'ABCB10P3',
 'ABCB10P4',
 'ABCB11',
 'ABCB4',
 'ABCB5',
 'ABCB6',
 'ABCB7',
 'ABCB8',
 'ABCB9',
 'ABCC1',
 'ABCC10',
 'ABCC11',
 'ABCC12',
 'ABCC13',
 'ABCC2',
 'ABCC3',
 'ABCC4',
 'ABCC5',
 'ABCC5-AS1',
 'ABCC6',
 'ABCC6P1',
 'ABCC6P2',
 'ABCC8',
 'ABCC9',
 'ABCD1',
 'ABCD1P2',
 'ABCD1P3',
 'ABCD1P4',
 'ABCD1P5',
 'ABCD2',
 'ABCD3',
 'ABCD4',
 'ABCE1',
 'ABCF1',
 'ABCF2',
 'ABCF2P1',
 'ABCF2P2',
 'ABCF3',
 'ABCG1',
 'ABCG2',
 'ABCG4',
 'ABCG5',
 'ABCG8',
 'ABHD1',
 'ABHD10',
 'ABHD11',
 'ABHD11-AS1',
 'ABHD12',
 'ABHD12B',
 'ABHD13',
 'ABHD14A',
 'ABHD14A-ACY1',
 'ABHD14B',
 'ABHD15',
 'ABHD16A',
 'ABHD16B',
 'ABHD17A',
 'ABHD17AP1',
 'ABHD17AP3',
 'ABHD17AP4',
 'ABHD17AP6',
 'ABHD17AP9',
 'ABHD17B',
 'ABHD17C',
 'ABHD18',
 'ABHD2',
 'ABHD3',
 'ABHD4',
 'ABHD5',
 'ABHD6',
 'ABHD7',
 'ABHD8',
 'ABHD9',
 'ABI1',
 'ABI2',
 'ABI3',
 'ABI3BP',
 'ABITRAM',
 'ABL1',
 'ABL2',
 'ABLIM1',
 'ABLIM2',
 'ABLIM3',
 'ABO',
 'ABP1',
 'ABR',
 'ABRA',
 'ABRACL',
 'ABRAXAS1',
 'ABRAXAS2',
 'ABT1',
 'ABT1P1',
 'ABTB1',
 'ABTB2',
 'ABTB3',
 'AC093375.1',
 'ACAA1',
 'ACAA2',
 'ACACA',
 'ACACB',
 'ACAD10',
 'ACAD11',
 'ACAD8',
 'ACAD9',
 'ACADL',
 'ACADM',
 'ACADS',
 'ACADSB',
 'ACADVL',
 'ACAN',
 'ACAP1',
 'ACAP2',
 'ACAP2-IT1',
 'ACAP3',
 'ACAT1',
 'ACAT2',
 'ACBD3',
 'ACBD4',
 'ACBD5',
 'ACBD6',
 'ACBD7',
 'ACCN1',
 'ACCN2',
 'ACCN3',
 'ACCN4',
 'ACCN5',
 'ACCS',
 'ACCSL',
 'ACD',
 'ACE',
 'ACE2',
 'ACE3P',
 'ACER1',
 'ACER2',
 'ACER3',
 'ACHE',
 'ACIN1',
 'ACKR1',
 'ACKR2',
 'ACKR3',
 'ACKR4',
 'ACLY',
 'ACMSD',
 'ACN9',
 'ACO1',
 'ACO2',
 'ACOD1',
 'ACOT1',
 'ACOT11',
 'ACOT12',
 'ACOT13',
 'ACOT2',
 'ACOT4',
 'ACOT6',
 'ACOT7',
 'ACOT8',
 'ACOT9',
 'ACOX1',
 'ACOX2',
 'ACOX3',
 'ACOXL',
 'ACOXL-AS1',
 'ACP1',
 'ACP2',
 'ACP3',
 'ACP4',
 'ACP5',
 'ACP6',
 'ACP7',
 'ACPL2',
 'ACPP',
 'ACPT',
 'ACR',
 'ACRBP',
 'ACRC',
 'ACRV1',
 'ACSBG1',
 'ACSBG2',
 'ACSF2',
 'ACSF3',
 'ACSL1',
 'ACSL3',
 'ACSL4',
 'ACSL5',
 'ACSL6',
 'ACSL6-AS1',
 'ACSM1',
 'ACSM2A',
 'ACSM2B',
 'ACSM3',
 'ACSM4',
 'ACSM5',
 'ACSM6',
 'ACSS1',
 'ACSS2',
 'ACSS3',
 'ACTA1',
 'ACTA2',
 'ACTA2-AS1',
 'ACTB',
 'ACTBL2',
 'ACTBP1',
 'ACTBP11',
 'ACTBP12',
 'ACTBP13',
 'ACTBP14',
 'ACTBP2',
 'ACTBP6',
 'ACTBP7',
 'ACTBP8',
 'ACTC1',
 'ACTE1P',
 'ACTG1',
 'ACTG1P1',
 'ACTG1P11',
 'ACTG1P12',
 'ACTG1P13',
 'ACTG1P14',
 'ACTG1P17',
 'ACTG1P2',
 'ACTG1P20',
 'ACTG1P25',
 'ACTG1P3',
 'ACTG1P4',
 'ACTG1P9',
 'ACTG2',
 'ACTL10',
 'ACTL6A',
 'ACTL6B',
 'ACTL7A',
 'ACTL7B',
 'ACTL8',
 'ACTL9',
 'ACTMAP',
 'ACTN1',
 'ACTN1-AS1',
 'ACTN1-DT',
 'ACTN2',
 'ACTN3',
 'ACTN4',
 'ACTN4P1',
 'ACTN4P2',
 'ACTR10',
 'ACTR1A',
 'ACTR1B',
 'ACTR2',
 'ACTR3',
 'ACTR3-AS1',
 'ACTR3B',
 'ACTR3BP2',
 'ACTR3BP3',
 'ACTR3BP4',
 'ACTR3BP5',
 'ACTR3BP6',
 'ACTR3C',
 'ACTR3P2',
 'ACTR3P3',
 'ACTR5',
 'ACTR6',
 'ACTR6P1',
 'ACTR8',
 'ACTRT1',
 'ACTRT2',
 'ACTRT3',
 'ACVR1',
 'ACVR1B',
 'ACVR1C',
 'ACVR2A',
 'ACVR2B',
 'ACVR2B-AS1',
 'ACVRL1',
 'ACY1',
 'ACY3',
 'ACYP1',
 'ACYP2',
 'ADA',
 'ADA2',
 'ADAD1',
 'ADAD2',
 'ADAL',
 'ADAM10',
 'ADAM11',
 'ADAM12',
 'ADAM15',
 'ADAM17',
 'ADAM18',
 'ADAM19',
 'ADAM1A',
 'ADAM1B',
 'ADAM2',
 'ADAM20',
 'ADAM20P1',
 'ADAM20P2',
 'ADAM20P3',
 'ADAM21',
 'ADAM21P',
 'ADAM21P1',
 'ADAM22',
 'ADAM23',
 'ADAM24P',
 'ADAM28',
 'ADAM29',
 'ADAM30',
 'ADAM32',
 'ADAM33',
 'ADAM3A',
 'ADAM3B',
 'ADAM5',
 'ADAM5P',
 'ADAM6',
 'ADAM7',
 'ADAM7-AS1',
 'ADAM7-AS2',
 'ADAM8',
 'ADAM9',
 'ADAMDEC1',
 'ADAMTS1',
 'ADAMTS10',
 'ADAMTS12',
 'ADAMTS13',
 'ADAMTS14',
 'ADAMTS15',
 'ADAMTS16',
 'ADAMTS16-DT',
 'ADAMTS17',
 'ADAMTS18',
 'ADAMTS19',
 'ADAMTS19-AS1',
 'ADAMTS2',
 'ADAMTS20',
 'ADAMTS3',
 'ADAMTS4',
 'ADAMTS5',
 'ADAMTS6',
 'ADAMTS7',
 'ADAMTS7P1',
 'ADAMTS7P3',
 'ADAMTS7P4',
 'ADAMTS8',
 'ADAMTS9',
 'ADAMTS9-AS1',
 'ADAMTS9-AS2',
 'ADAMTSL1',
 'ADAMTSL2',
 'ADAMTSL3',
 'ADAMTSL4',
 'ADAMTSL4-AS1',
 'ADAMTSL5',
 'ADAP1',
 'ADAP2',
 'ADAR',
 'ADARB1',
 'ADARB2',
 'ADARB2-AS1',
 'ADAT1',
 'ADAT2',
 'ADAT3',
 'ADC',
 'ADCK1',
 'ADCK2',
 'ADCK3',
 'ADCK4',
 'ADCK5',
 'ADCY1',
 'ADCY10',
 'ADCY10P1',
 'ADCY2',
 'ADCY3',
 'ADCY4',
 'ADCY5',
 'ADCY6',
 'ADCY6-DT',
 'ADCY7',
 'ADCY8',
 'ADCY9',
 'ADCYAP1',
 'ADCYAP1R1',
 'ADD1',
 'ADD2',
 'ADD3',
 'ADD3-AS1',
 'ADGB',
 'ADGB-DT',
 'ADGRA1',
 'ADGRA1-AS1',
 'ADGRA2',
 'ADGRA3',
 'ADGRB1',
 'ADGRB2',
 'ADGRB3',
 'ADGRB3-DT',
 'ADGRD1',
 'ADGRD2',
 'ADGRE1',
 'ADGRE2',
 'ADGRE3',
 'ADGRE4P',
 'ADGRE5',
 'ADGRF1',
 'ADGRF2',
 'ADGRF3',
 'ADGRF4',
 'ADGRF5',
 'ADGRF5-AS1',
 'ADGRG1',
 'ADGRG2',
 'ADGRG3',
 'ADGRG4',
 'ADGRG5',
 'ADGRG6',
 'ADGRG7',
 'ADGRL1',
 'ADGRL1-AS1',
 'ADGRL2',
 'ADGRL3',
 'ADGRL3-AS1',
 'ADGRL4',
 'ADGRV1',
 'ADH1A',
 'ADH1B',
 'ADH1C',
 'ADH4',
 'ADH5',
 'ADH5P2',
 'ADH5P3',
 'ADH5P4',
 'ADH6',
 'ADH7',
 'ADHFE1',
 'ADI1',
 'ADIG',
 'ADIPOQ',
 'ADIPOQ-AS1',
 'ADIPOR1',
 'ADIPOR1P1',
 'ADIPOR1P2',
 'ADIPOR2',
 'ADIRF',
 'ADISSP',
 'ADK',
 'ADM',
 'ADM2',
 'ADM5',
 'ADNP',
 'ADNP-AS1',
 'ADNP2',
 'ADO',
 'ADORA1',
 'ADORA2A',
 'ADORA2A-AS1',
 'ADORA2B',
 'ADORA2BP1',
 'ADORA3',
 'ADPGK',
 'ADPGK-AS1',
 'ADPRH',
 'ADPRHL1',
 'ADPRHL2',
 'ADPRM',
 'ADPRS',
 'ADRA1A',
 'ADRA1B',
 'ADRA1D',
 'ADRA2A',
 'ADRA2B',
 'ADRA2C',
 'ADRB1',
 'ADRB2',
 'ADRB3',
 'ADRBK1',
 'ADRBK2',
 'ADRM1',
 'ADSL',
 'ADSS',
 'ADSS1',
 'ADSS2',
 'ADSSL1',
 'ADTRP',
 'AEBP1',
 'AEBP2',
 'AEN',
 'AES',
 'AFAP1',
 'AFAP1-AS1',
 'AFAP1L1',
 'AFAP1L2',
 'AFAR3',
 'AFARP1',
 'AFDN',
 'AFDN-DT',
 'AFF1',
 'AFF1-AS1',
 'AFF2',
 'AFF2-IT1',
 'AFF3',
 'AFF4',
 'AFG1L',
 'AFG2A',
 'AFG2B',
 'AFG3L1',
 'AFG3L1P',
 'AFG3L2',
 'AFG3L2P1',
 'AFM',
 'AFMID',
 'AFP',
 'AFTPH',
 'AFTPH-DT',
 'AGA',
 'AGAP1',
 'AGAP1-IT1',
 'AGAP11',
 'AGAP12P',
 'AGAP2',
 'AGAP2-AS1',
 'AGAP3',
 'AGAP4',
 'AGAP5',
 'AGAP6',
 'AGAP6 (includes others)',
 'AGAP7',
 'AGAP7P',
 'AGAP8',
 'AGAP9',
 'AGBL1',
 'AGBL1-AS1',
 'AGBL2',
 'AGBL3',
 'AGBL4',
 'AGBL4-AS1',
 'AGBL4-IT1',
 'AGBL5',
 'AGBL5-AS1',
 'AGC1',
 'AGER',
 'AGFG1',
 'AGFG2',
 'AGGF1',
 'AGGF1P1',
 'AGGF1P2',
 'AGGF1P3',
 'AGGF1P4',
 'AGK',
 'AGKP1',
 'AGL',
 'AGMAT',
 'AGMO',
 'AGO1',
 'AGO2',
 'AGO3',
 'AGO4',
 'AGPAT1',
 'AGPAT2',
 'AGPAT3',
 'AGPAT4',
 'AGPAT4-IT1',
 'AGPAT5',
 'AGPAT5P1',
 'AGPAT6',
 'AGPAT9',
 'AGPS',
 'AGR2',
 'AGR3',
 'AGRN',
 'AGRP',
 'AGT',
 'AGTPBP1',
 'AGTR1',
 'AGTR2',
 'AGTRAP',
 'AGXT',
 'AGXT2',
 'AGXT2L1',
 'AGXT2L2',
 'AHCTF1',
 'AHCTF1P1',
 'AHCY',
 'AHCYL1',
 'AHCYL2',
 'AHCYP2',
 'AHCYP3',
 'AHCYP4',
 'AHCYP5',
 'AHCYP7',
 'AHDC1',
 'AHI1',
 'AHI1-DT',
 'AHNAK',
 'AHNAK2',
 'AHR',
 'AHRR',
 'AHSA1',
 'AHSA2',
 'AHSA2P',
 'AHSG',
 'AHSP',
 'AICDA',
 'AIDA',
 'AIF1',
 'AIF1L',
 'AIFM1',
 'AIFM1P1',
 'AIFM2',
 'AIFM3',
 'AIG1',
 'AIM1',
 'AIM1L',
 'AIM2',
 'AIMP1',
 'AIMP1P1',
 'AIMP1P2',
 'AIMP2',
 'AIP',
 'AIPL1',
 'AIRE',
 'AIRIM',
 'AIRN',
 'AJAP1',
 'AJM1',
 'AJUBA',
 'AK1',
 'AK2',
 'AK2P2',
 'AK3',
 'AK3L1',
 'AK3P2',
 'AK3P3',
 'AK3P4',
 'AK3P5',
 'AK4',
 'AK4P1',
 'AK4P2',
 'AK4P3',
 'AK4P4',
 'AK4P5',
 'AK4P6',
 'AK5',
 'AK6',
 'AK7',
 'AK8',
 'AK9',
 'AKAIN1',
 'AKAP1',
 'AKAP10',
 'AKAP11',
 'AKAP12',
 'AKAP13',
 'AKAP14',
 'AKAP17A',
 'AKAP17BP',
 'AKAP2',
 'AKAP3',
 'AKAP4',
 'AKAP5',
 'AKAP6',
 'AKAP7',
 'AKAP8',
 'AKAP8L',
 'AKAP8P1',
 'AKAP9',
 'AKIP1',
 'AKIRIN1',
 'AKIRIN1P1',
 'AKIRIN2',
 'AKIRIN2P1',
 'AKNA',
 'AKNAD1',
 'AKR1A1',
 'AKR1B1',
 'AKR1B10',
 'AKR1B10P1',
 'AKR1B10P2',
 'AKR1B15',
 'AKR1B1P1',
 'AKR1B1P2',
 'AKR1B1P4',
 'AKR1B1P6',
 'AKR1B1P8',
 'AKR1C1',
 'AKR1C1/AKR1C2',
 'AKR1C2',
 'AKR1C3',
 'AKR1C4',
 'AKR1C5P',
 'AKR1C6P',
 'AKR1C7P',
 'AKR1C8',
 'AKR1CL1',
 'AKR1D1',
 'AKR1D1P1',
 'AKR1E2',
 'AKR7A2',
 'AKR7A2P1',
 'AKR7A3',
 'AKR7L',
 'AKT1',
 'AKT1S1',
 'AKT2',
 'AKT3',
 'AKT3-IT1',
 'AKTIP',
 'ALAD',
 'ALAS1',
 'ALAS2',
 'ALB',
 'ALCAM',
 'ALDH16A1',
 'ALDH18A1',
 'ALDH1A1',
 'ALDH1A2',
 'ALDH1A3',
 'ALDH1A3-AS1',
 'ALDH1B1',
 'ALDH1L1',
 'ALDH1L1-AS1',
 'ALDH1L1-AS2',
 'ALDH1L2',
 'ALDH2',
 'ALDH3A1',
 'ALDH3A2',
 'ALDH3B1',
 'ALDH3B2',
 'ALDH4A1',
 'ALDH5A1',
 'ALDH6A1',
 'ALDH7A1',
 'ALDH7A1P1',
 'ALDH7A1P2',
 'ALDH7A1P3',
 'ALDH7A1P4',
 'ALDH8A1',
 'ALDH9A1',
 'ALDOA',
 'ALDOAP1',
 'ALDOAP2',
 'ALDOB',
 'ALDOC',
 'ALG1',
 'ALG10',
 'ALG10B',
 'ALG11',
 'ALG12',
 'ALG13',
 'ALG14',
 'ALG14-AS1',
 'ALG1L',
 'ALG1L12P',
 'ALG1L14P',
 'ALG1L15P',
 'ALG1L1P',
 'ALG1L2',
 'ALG1L3P',
 'ALG1L5P',
 'ALG1L6P',
 'ALG1L7P',
 'ALG1L8P',
 'ALG1L9P',
 'ALG2',
 'ALG3',
 'ALG3P1',
 'ALG5',
 'ALG6',
 'ALG8',
 'ALG9',
 'ALG9-IT1',
 'ALK',
 'ALKAL1',
 'ALKAL2',
 'ALKBH1',
 'ALKBH2',
 'ALKBH3',
 'ALKBH3-AS1',
 'ALKBH4',
 'ALKBH5',
 'ALKBH6',
 'ALKBH7',
 'ALKBH8',
 'ALLC',
 'ALMS1',
 'ALMS1-IT1',
 'ALMS1P',
 'ALMS1P1',
 'ALOX12',
 'ALOX12-AS1',
 'ALOX12B',
 'ALOX12P1',
 'ALOX12P2',
 'ALOX15',
 'ALOX15B',
 'ALOX15P1',
 'ALOX15P2',
 'ALOX5',
 'ALOX5AP',
 'ALOXE3',
 'ALPG',
 'ALPI',
 'ALPK1',
 'ALPK2',
 'ALPK3',
 'ALPL',
 'ALPP',
 'ALPPL2',
 'ALS2',
 'ALS2CL',
 'ALS2CR11',
 'ALS2CR12',
 'ALS2CR14',
 'ALS2CR16',
 'ALS2CR4',
 'ALS2CR8',
 'ALX1',
 'ALX3',
 'ALX4',
 'ALYREF',
 'AMAC1',
 'AMAC1L1',
 'AMAC1L2',
 'AMAC1L3',
 'AMACR',
 'AMBN',
 'AMBP',
 'AMBRA1',
 'AMD1',
 'AMD1P1',
 'AMDHD1',
 'AMDHD2',
 'AMDP1',
 'AMELX',
 'AMELY',
 'AMER1',
 'AMER2',
 'AMER3',
 'AMFR',
 'AMH',
 'AMHR2',
 'AMICA1',
 'AMIGO1',
 'AMIGO2',
 'AMIGO3',
 'AMMECR1',
 'AMMECR1-IT1',
 'AMMECR1L',
 'AMMECR1LP1',
 'AMN',
 'AMN1',
 'AMOT',
 'AMOTL1',
 'AMOTL2',
 'AMPD1',
 'AMPD2',
 'AMPD3',
 'AMPH',
 'AMT',
 'AMTN',
 'AMY1A',
 'AMY1A (includes others)',
 'AMY1B',
 'AMY1C',
 'AMY2A',
 'AMY2B',
 'AMYP1',
 'AMZ1',
 'AMZ2',
 'AMZ2P1',
 'AMZ2P2',
 'ANAPC1',
 'ANAPC10',
 'ANAPC10P1',
 'ANAPC11',
 'ANAPC13',
 'ANAPC15',
 'ANAPC16',
 'ANAPC1P1',
 'ANAPC1P2',
 'ANAPC1P4',
 'ANAPC2',
 'ANAPC4',
 'ANAPC5',
 'ANAPC7',
 'ANG',
 'ANGEL1',
 'ANGEL2',
 'ANGPT1',
 'ANGPT2',
 'ANGPT4',
 'ANGPTL1',
 'ANGPTL2',
 'ANGPTL3',
 'ANGPTL4',
 'ANGPTL5',
 'ANGPTL6',
 'ANGPTL7',
 'ANGPTL8',
 'ANHX',
 'ANK1',
 'ANK2',
 'ANK3',
 'ANKAR',
 'ANKDD1A',
 'ANKDD1B',
 'ANKEF1',
 'ANKFN1',
 'ANKFY1',
 'ANKH',
 'ANKHD1',
 'ANKHD1-EIF4EBP3',
 'ANKHD1/ANKHD1-EIF4EBP3',
 'ANKIB1',
 'ANKK1',
 'ANKLE1',
 'ANKLE2',
 'ANKMY1',
 'ANKMY2',
 'ANKRA2',
 'ANKRD1',
 'ANKRD10',
 'ANKRD10-IT1',
 'ANKRD11',
 'ANKRD12',
 'ANKRD13A',
 'ANKRD13B',
 'ANKRD13C',
 'ANKRD13C-DT',
 'ANKRD13D',
 'ANKRD16',
 'ANKRD17',
 'ANKRD17-DT',
 'ANKRD18A',
 'ANKRD18B',
 'ANKRD18CP',
 'ANKRD18DP',
 'ANKRD18EP',
 'ANKRD19',
 'ANKRD19P',
 ...]

In [109]:
gex = clinical_gex.iloc[:, len(CLINICAL_COLS)-2:]
gex

,sample_id,7A5,A1BG,A1BG-AS1,A1CF,A26C3,A2BP1,A2LD1,A2M,A2M-AS1,...,sept-05,sept-06,sept-07,sept-08,sept-09,sept-10,sept-11,sept-12,sept-14,sept-15
0,03660555B,NaN,NaN,1.029729,0.013240,NaN,NaN,NaN,NaN,16.754174,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,03660598B,NaN,NaN,1.600817,0.008137,NaN,NaN,NaN,NaN,42.862157,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03660602B,NaN,NaN,1.761795,0.013022,NaN,NaN,NaN,NaN,20.930385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04240076F,NaN,NaN,0.771063,0.009576,NaN,NaN,NaN,NaN,13.671007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04240106F,NaN,NaN,1.473717,0.001873,NaN,NaN,NaN,NaN,16.397558,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,Pt4-baseline,NaN,5.074610,0.653775,0.000000,NaN,NaN,NaN,499.750500,2.473420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Pt10-baseline,NaN,14.780750,0.271060,0.000000,NaN,NaN,NaN,105.804500,4.074100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,Pt16-baseline,NaN,0.961217,0.100338,0.000000,NaN,NaN,NaN,287.821667,3.230953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,Pt17-baseline,NaN,3.040353,0.420437,0.002556,NaN,NaN,NaN,245.584667,1.424927,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,Pt6-baseline,NaN,4.186100,0.512325,0.000000,NaN,NaN,NaN,94.295767,0.093898,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
print(gex['sample_id'])

0          03660555B
1          03660598B
2          03660602B
3          04240076F
4          04240106F
           ...
129     Pt4-baseline
130    Pt10-baseline
131    Pt16-baseline
132    Pt17-baseline
133     Pt6-baseline
Name: sample_id, Length: 134, dtype: object

In [114]:
gex_mat = gex.set_index('sample_id').T
gex_mat

sample_id,03660555B,03660598B,03660602B,04240076F,04240106F,04240120C,04240151B,05320003B,05320011B,05320012B,...,Pt1-baseline,Pt5-baseline,Pt9-baseline,Pt8-baseline,Pt2-baseline,Pt4-baseline,Pt10-baseline,Pt16-baseline,Pt17-baseline,Pt6-baseline
7A5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A1BG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.357535,12.442250,7.154420,9.517875,6.608285,5.074610,14.78075,0.961217,3.040353,4.186100
A1BG-AS1,1.029729,1.600817,1.761795,0.771063,1.473717,1.065738,1.794694,1.595717,0.509797,0.243509,...,2.648650,0.734388,1.023753,1.568550,0.674266,0.653775,0.27106,0.100338,0.420437,0.512325
A1CF,0.013240,0.008137,0.013022,0.009576,0.001873,0.000000,0.008215,0.003275,0.003053,0.000000,...,0.019940,0.000000,0.004563,0.002085,0.001765,0.000000,0.00000,0.000000,0.002556,0.000000
A26C3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sept-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sept-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sept-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sept-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sept-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
sample_source = clinical_gex[['sample_id', 'source', 'patientID', 'pfs_label']]
sample_source

         sample_id       source  patientID  pfs_label
0        03660555B   Yan et al.    YR_3053          0
1        03660598B   Yan et al.    YR_3708          2
2        03660602B   Yan et al.    YR_3705          2
3        04240076F   Yan et al.    YR_1106          0
4        04240106F   Yan et al.    YR_1110          0
..             ...          ...        ...        ...
129   Pt4-baseline  Hugo et al.  HL_Shi-35          1
130  Pt10-baseline  Hugo et al.  HL_Shi-37          2
131  Pt16-baseline  Hugo et al.  HL_Shi-38          0
132  Pt17-baseline  Hugo et al.  HL_Shi-43          1
133   Pt6-baseline  Hugo et al.  HL_Shi-44          0

[134 rows x 4 columns]

In [115]:
sample_source.to_csv(f"../dataset/created/sample_source.csv", index=False)
gex_mat.index.name = 'sample_id'
gex_mat.to_csv(f"../dataset/created/gex_mat.csv", index=True)