# 3. Create sample-source metadata

## Read GEX_MAT

In [19]:
import polars as pl
gex_mat = pl.read_csv(f'../dataset/created/gex_mat.csv')
gex_mat

shape: (51_465, 144)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ HGNC      ┆ 28094     ┆ 05320216B ┆ Pt1-basel ┆ … ┆ 05320119C ┆ 03660598B ┆ 45413     ┆ 05320444 │
│ ---       ┆ PreB      ┆ ---       ┆ ine       ┆   ┆ ---       ┆ ---       ┆ PreC      ┆ B        │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ f64       ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ BCLAF1    ┆ 1207.282  ┆ 4.237369  ┆ 30.4908   ┆ … ┆ 7.327778  ┆ 5.467553  ┆ 575.8395  ┆ 8.754171 │
│ PLA2G4E   ┆ 2.850116  ┆ 0.036089  ┆ 0.055628  ┆ … ┆ 6.09182   ┆ 0.042667  ┆ 8.587088  ┆ 0.0      │
│ PPP1R9A   ┆ 22.14266  ┆ 1.307164  ┆ 0.395961  ┆ … ┆ 2.988701  ┆ 4.596764  ┆ 52.05827  ┆ 25.08646 │
│ LOC653232 ┆ 11541.6   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 8720.374  ┆ null     │
│ PMP22     ┆ 3411.054  ┆ 54.578361 ┆ 151.8825  ┆ … ┆ 33.094721 ┆ 17.671529 ┆ 3706.45   ┆ 39.05374 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ HMGB3P17  ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ FTH1P14   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ HDHD1P3   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ RNA5SP502 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ mir-1281  ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Read GEX

In [20]:
gex = pl.read_csv(f"../dataset/created/gex.csv")
gex

shape: (4_162_394, 6)
┌────────────┬─────────────────┬───────────┬───────────┬──────────────┬─────────────┐
│ patientID  ┆ sample_id       ┆ HGNC      ┆ value     ┆ source       ┆ Method      │
│ ---        ┆ ---             ┆ ---       ┆ ---       ┆ ---          ┆ ---         │
│ str        ┆ str             ┆ str       ┆ f64       ┆ str          ┆ str         │
╞════════════╪═════════════════╪═══════════╪═══════════╪══════════════╪═════════════╡
│ LR_MTP-009 ┆ 28094 PreB      ┆ BCLAF1    ┆ 1207.282  ┆ Long et al.  ┆ micro-array │
│ YR_2220    ┆ 05320216B       ┆ PLA2G4E   ┆ 0.036089  ┆ Yan et al.   ┆ RNA-seq     │
│ HL_Shi-15  ┆ Pt1-baseline    ┆ PPP1R9A   ┆ 0.395961  ┆ Hugo et al.  ┆ RNA-seq     │
│ LR_MTP-034 ┆ 28518_049E PreC ┆ LOC653232 ┆ 11346.65  ┆ Long et al.  ┆ micro-array │
│ KC_16      ┆ 16A             ┆ PMP22     ┆ 49.22     ┆ Kwong et al. ┆ RNA-seq     │
│ …          ┆ …               ┆ …         ┆ …         ┆ …            ┆ …           │
│ RL_WMD-007 ┆ 28067_010A PreB ┆ LOC646743 ┆ 8.428306  ┆ Rizos et al. ┆ micro-array │
│ RL_WMD-027 ┆ 30230_077K PreB ┆ CD160     ┆ 0.2476966 ┆ Rizos et al. ┆ micro-array │
│ YR_2378    ┆ 05320239B       ┆ ELAPOR1   ┆ 0.747924  ┆ Yan et al.   ┆ RNA-seq     │
│ RL_WMD-027 ┆ 30230_077K PreB ┆ HNMT      ┆ 472.3288  ┆ Rizos et al. ┆ micro-array │
│ YR_2220    ┆ 05320216B       ┆ SOWAHA    ┆ 0.0       ┆ Yan et al.   ┆ RNA-seq     │
└────────────┴─────────────────┴───────────┴───────────┴──────────────┴─────────────┘

## Fitler GEX col -> sample_source

In [21]:
sample_source = (
    gex
    .select(["sample_id", "source", 'patientID'])
    .unique()
)
sample_source

shape: (143, 3)
┌─────────────────┬──────────────┬────────────┐
│ sample_id       ┆ source       ┆ patientID  │
│ ---             ┆ ---          ┆ ---        │
│ str             ┆ str          ┆ str        │
╞═════════════════╪══════════════╪════════════╡
│ 05320102B       ┆ Yan et al.   ┆ YR_2362    │
│ 8766_022H PreC  ┆ Long et al.  ┆ LR_WMD-022 │
│ 05320012B       ┆ Yan et al.   ┆ YR_2203    │
│ 9A              ┆ Kwong et al. ┆ KC_9       │
│ 2A              ┆ Kwong et al. ┆ KC_2       │
│ …               ┆ …            ┆ …          │
│ 05420145C       ┆ Yan et al.   ┆ YR_106008  │
│ 27473_049K PreB ┆ Rizos et al. ┆ RL_WMD-039 │
│ 05320184B       ┆ Yan et al.   ┆ YR_2319    │
│ Pt9-baseline    ┆ Hugo et al.  ┆ HL_Shi-23  │
│ 05320232B       ┆ Yan et al.   ┆ YR_2207    │
└─────────────────┴──────────────┴────────────┘

In [22]:
sample_source['patientID'].value_counts(sort=True)  # There are duplicated patientIDs

shape: (126, 2)
┌────────────┬───────┐
│ patientID  ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ LR_MTP-009 ┆ 5     │
│ LR_WMD-022 ┆ 2     │
│ LR_WMD-017 ┆ 2     │
│ RL_MTP-063 ┆ 2     │
│ RL_WMD-027 ┆ 2     │
│ …          ┆ …     │
│ YR_2484    ┆ 1     │
│ YR_106008  ┆ 1     │
│ YR_2319    ┆ 1     │
│ HL_Shi-23  ┆ 1     │
│ YR_2207    ┆ 1     │
└────────────┴───────┘

## Read Clinical for getting Target class

In [23]:
clinical = pl.read_csv(f'../dataset/created/clinical.csv')
clinical

shape: (415, 26)
┌─────┬───────────┬────────┬─────┬───┬─────┬───────┬───────┬───────┐
│     ┆ patientID ┆ sex    ┆ age ┆ … ┆ MND ┆ V600E ┆ V600K ┆ V600R │
│ --- ┆ ---       ┆ ---    ┆ --- ┆   ┆ --- ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ str       ┆ str    ┆ i64 ┆   ┆ i64 ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═══════════╪════════╪═════╪═══╪═════╪═══════╪═══════╪═══════╡
│ 0   ┆ BS_000    ┆ male   ┆ 56  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 1   ┆ BS_001    ┆ male   ┆ 86  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 2   ┆ BS_002    ┆ female ┆ 47  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 3   ┆ BS_003    ┆ female ┆ 50  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 4   ┆ BS_004    ┆ female ┆ 47  ┆ … ┆ 0   ┆ 0     ┆ 1     ┆ 0     │
│ …   ┆ …         ┆ …      ┆ …   ┆ … ┆ …   ┆ …     ┆ …     ┆ …     │
│ 410 ┆ HL_40     ┆ male   ┆ 47  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 411 ┆ HL_41     ┆ male   ┆ 39  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 412 ┆ HL_42     ┆ male   ┆ 84  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 413 ┆ HL_43     ┆ female ┆ 41  ┆ … ┆ 0   ┆ 1     ┆ 0     ┆ 0     │
│ 414 ┆ HL_44     ┆ male   ┆ 83  ┆ … ┆ 0   ┆ 0     ┆ 1     ┆ 0     │
└─────┴───────────┴────────┴─────┴───┴─────┴───────┴───────┴───────┘

## Reorder sample_source sampleIDs according to gex_mat sampleIDs

In [24]:
# Get column order from gex_mat (excluding HGNC)
col_order = gex_mat.columns[1:]  # skip HGNC

# Reorder sample_source rows to match gex_mat column order
sample_source_reordered = (
    pl.DataFrame({"sample_id": col_order})
    .join(sample_source, on="sample_id", how="left")
)


sample_source_reordered

shape: (143, 3)
┌─────────────────┬──────────────┬────────────┐
│ sample_id       ┆ source       ┆ patientID  │
│ ---             ┆ ---          ┆ ---        │
│ str             ┆ str          ┆ str        │
╞═════════════════╪══════════════╪════════════╡
│ 28094 PreB      ┆ Long et al.  ┆ LR_MTP-009 │
│ 05320216B       ┆ Yan et al.   ┆ YR_2220    │
│ Pt1-baseline    ┆ Hugo et al.  ┆ HL_Shi-15  │
│ 28518_049E PreC ┆ Long et al.  ┆ LR_MTP-034 │
│ 16A             ┆ Kwong et al. ┆ KC_16      │
│ …               ┆ …            ┆ …          │
│ Pt10-baseline   ┆ Hugo et al.  ┆ HL_Shi-37  │
│ 05320119C       ┆ Yan et al.   ┆ YR_2347    │
│ 03660598B       ┆ Yan et al.   ┆ YR_3708    │
│ 45413 PreC      ┆ Long et al.  ┆ LR_MTP-073 │
│ 05320444B       ┆ Yan et al.   ┆ YR_2466    │
└─────────────────┴──────────────┴────────────┘

## Add Target class

In [25]:
sample_source_reordered = (
    sample_source_reordered
    .join(
        clinical.select(["patientID", "pfs_label"]),
        on="patientID",
        how="left"
    )
).drop_nulls(pl.col('pfs_label'))
sample_source_reordered

shape: (125, 4)
┌─────────────────┬──────────────┬────────────┬───────────┐
│ sample_id       ┆ source       ┆ patientID  ┆ pfs_label │
│ ---             ┆ ---          ┆ ---        ┆ ---       │
│ str             ┆ str          ┆ str        ┆ i64       │
╞═════════════════╪══════════════╪════════════╪═══════════╡
│ 05320216B       ┆ Yan et al.   ┆ YR_2220    ┆ 0         │
│ 28518_049E PreC ┆ Long et al.  ┆ LR_MTP-034 ┆ 0         │
│ 16A             ┆ Kwong et al. ┆ KC_16      ┆ 1         │
│ 05420159C       ┆ Yan et al.   ┆ YR_103001  ┆ 0         │
│ 05320093C       ┆ Yan et al.   ┆ YR_2096    ┆ 2         │
│ …               ┆ …            ┆ …          ┆ …         │
│ 08626 PreC      ┆ Long et al.  ┆ LR_WMD-033 ┆ 0         │
│ 05320119C       ┆ Yan et al.   ┆ YR_2347    ┆ 0         │
│ 03660598B       ┆ Yan et al.   ┆ YR_3708    ┆ 2         │
│ 45413 PreC      ┆ Long et al.  ┆ LR_MTP-073 ┆ 0         │
│ 05320444B       ┆ Yan et al.   ┆ YR_2466    ┆ 2         │
└─────────────────┴──────────────┴────────────┴───────────┘

## Filter GEX_MAT to have same samples as sample_source

In [26]:
valid_samples = sample_source_reordered["sample_id"].to_list()
cols_to_keep = ["HGNC"] + [c for c in gex_mat.columns if c in valid_samples]
gex_mat_filtered = gex_mat.select(cols_to_keep)

gex_mat_filtered

shape: (51_465, 126)
┌───────────┬───────────┬─────────────┬───────┬───┬───────────┬───────────┬────────────┬───────────┐
│ HGNC      ┆ 05320216B ┆ 28518_049E  ┆ 16A   ┆ … ┆ 05320119C ┆ 03660598B ┆ 45413 PreC ┆ 05320444B │
│ ---       ┆ ---       ┆ PreC        ┆ ---   ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---       │
│ str       ┆ f64       ┆ ---         ┆ f64   ┆   ┆ f64       ┆ f64       ┆ f64        ┆ f64       │
│           ┆           ┆ f64         ┆       ┆   ┆           ┆           ┆            ┆           │
╞═══════════╪═══════════╪═════════════╪═══════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ BCLAF1    ┆ 4.237369  ┆ 235.4447    ┆ 17.26 ┆ … ┆ 7.327778  ┆ 5.467553  ┆ 575.8395   ┆ 8.754171  │
│ PLA2G4E   ┆ 0.036089  ┆ 4.696824    ┆ 0.03  ┆ … ┆ 6.09182   ┆ 0.042667  ┆ 8.587088   ┆ 0.0       │
│ PPP1R9A   ┆ 1.307164  ┆ 1.309181    ┆ 3.87  ┆ … ┆ 2.988701  ┆ 4.596764  ┆ 52.05827   ┆ 25.08646  │
│ LOC653232 ┆ null      ┆ 11346.65    ┆ null  ┆ … ┆ null      ┆ null      ┆ 8720.374   ┆ null      │
│ PMP22     ┆ 54.578361 ┆ 3891.525    ┆ 49.22 ┆ … ┆ 33.094721 ┆ 17.671529 ┆ 3706.45    ┆ 39.053741 │
│ …         ┆ …         ┆ …           ┆ …     ┆ … ┆ …         ┆ …         ┆ …          ┆ …         │
│ HMGB3P17  ┆ null      ┆ null        ┆ 0.0   ┆ … ┆ null      ┆ null      ┆ null       ┆ null      │
│ FTH1P14   ┆ null      ┆ null        ┆ 0.0   ┆ … ┆ null      ┆ null      ┆ null       ┆ null      │
│ HDHD1P3   ┆ null      ┆ null        ┆ 0.0   ┆ … ┆ null      ┆ null      ┆ null       ┆ null      │
│ RNA5SP502 ┆ null      ┆ null        ┆ 0.0   ┆ … ┆ null      ┆ null      ┆ null       ┆ null      │
│ mir-1281  ┆ null      ┆ null        ┆ 0.0   ┆ … ┆ null      ┆ null      ┆ null       ┆ null      │
└───────────┴───────────┴─────────────┴───────┴───┴───────────┴───────────┴────────────┴───────────┘

In [27]:
sample_source_reordered.write_csv(f"../dataset/created/sample_source.csv")
gex_mat_filtered.write_csv(f"../dataset/created/gex_mat.csv")