# 4. Merge Clinical and Corrected GEX_MAT

## Read datasets

In [25]:
import polars as pl

clinical = pl.read_csv(f"../dataset/created/clinical.csv")
clinical

shape: (415, 23)
┌─────┬───────────┬────────┬─────┬───┬───────┬───────┬───────┬───────┐
│     ┆ patientID ┆ sex    ┆ age ┆ … ┆ R558Q ┆ V600E ┆ V600K ┆ V600R │
│ --- ┆ ---       ┆ ---    ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ str       ┆ str    ┆ i64 ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═══════════╪════════╪═════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ 0   ┆ BS_000    ┆ male   ┆ 56  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 1   ┆ BS_001    ┆ male   ┆ 86  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 2   ┆ BS_002    ┆ female ┆ 47  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 3   ┆ BS_003    ┆ female ┆ 50  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 4   ┆ BS_004    ┆ female ┆ 47  ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ …   ┆ …         ┆ …      ┆ …   ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ 410 ┆ HL_40     ┆ male   ┆ 47  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 411 ┆ HL_41     ┆ male   ┆ 39  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 412 ┆ HL_42     ┆ male   ┆ 84  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 413 ┆ HL_43     ┆ female ┆ 41  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 414 ┆ HL_44     ┆ male   ┆ 83  ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
└─────┴───────────┴────────┴─────┴───┴───────┴───────┴───────┴───────┘

In [26]:
gex_mat = pl.read_csv(f"../dataset/created/gex_mat_corrected_sig.csv")
gex_mat

shape: (113, 126)
┌──────────┬───────────┬────────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HGNC     ┆ 05320216B ┆ 28518_049E ┆ 16A      ┆ … ┆ 05320119C ┆ 03660598B ┆ 45413     ┆ 05320444B │
│ ---      ┆ ---       ┆ PreC       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ PreC      ┆ ---       │
│ str      ┆ f64       ┆ ---        ┆ f64      ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│          ┆           ┆ f64        ┆          ┆   ┆           ┆           ┆ f64       ┆           │
╞══════════╪═══════════╪════════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BAIAP2L1 ┆ 6.008745  ┆ 7.821183   ┆ 5.576383 ┆ … ┆ 6.134985  ┆ 6.018943  ┆ 2.944774  ┆ 6.08192   │
│ VCX3A    ┆ 5.504085  ┆ 4.286877   ┆ 5.827332 ┆ … ┆ 5.518592  ┆ 5.540102  ┆ 4.467366  ┆ 5.510745  │
│ SV2B     ┆ 4.886019  ┆ 3.897034   ┆ 5.048343 ┆ … ┆ 4.887109  ┆ 4.904131  ┆ 4.267894  ┆ 4.895287  │
│ GNB5     ┆ 5.889565  ┆ 6.097602   ┆ 5.523008 ┆ … ┆ 5.692107  ┆ 5.759198  ┆ 6.348304  ┆ 5.709655  │
│ VCX2     ┆ 5.689952  ┆ 4.726301   ┆ 5.969492 ┆ … ┆ 5.692916  ┆ 5.697565  ┆ 4.120078  ┆ 5.689952  │
│ …        ┆ …         ┆ …          ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SEMA3A   ┆ 4.439806  ┆ 3.158478   ┆ 5.966681 ┆ … ┆ 4.551751  ┆ 4.470933  ┆ 6.144414  ┆ 7.638748  │
│ HIGD1B   ┆ 4.38366   ┆ 5.79525    ┆ 4.120395 ┆ … ┆ 4.392305  ┆ 4.334177  ┆ 5.634533  ┆ 4.357164  │
│ CDO1     ┆ 5.058616  ┆ 3.938261   ┆ 4.947229 ┆ … ┆ 5.045629  ┆ 5.050975  ┆ 6.057534  ┆ 5.086221  │
│ FGF13    ┆ 5.243796  ┆ 6.333221   ┆ 5.004979 ┆ … ┆ 5.260428  ┆ 5.253968  ┆ 6.618716  ┆ 5.270644  │
│ CKAP5    ┆ 7.43921   ┆ 6.723939   ┆ 7.937973 ┆ … ┆ 7.484392  ┆ 7.597721  ┆ 7.470223  ┆ 7.988817  │
└──────────┴───────────┴────────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [27]:
sample_source = pl.read_csv(f"../dataset/created/sample_source.csv")
sample_source

shape: (125, 4)
┌─────────────────┬──────────────┬────────────┬───────────┐
│ sample_id       ┆ source       ┆ patientID  ┆ pfs_label │
│ ---             ┆ ---          ┆ ---        ┆ ---       │
│ str             ┆ str          ┆ str        ┆ i64       │
╞═════════════════╪══════════════╪════════════╪═══════════╡
│ 05320216B       ┆ Yan et al.   ┆ YR_2220    ┆ 0         │
│ 28518_049E PreC ┆ Long et al.  ┆ LR_MTP-034 ┆ 0         │
│ 16A             ┆ Kwong et al. ┆ KC_16      ┆ 1         │
│ 05420159C       ┆ Yan et al.   ┆ YR_103001  ┆ 0         │
│ 05320093C       ┆ Yan et al.   ┆ YR_2096    ┆ 2         │
│ …               ┆ …            ┆ …          ┆ …         │
│ 08626 PreC      ┆ Long et al.  ┆ LR_WMD-033 ┆ 0         │
│ 05320119C       ┆ Yan et al.   ┆ YR_2347    ┆ 0         │
│ 03660598B       ┆ Yan et al.   ┆ YR_3708    ┆ 2         │
│ 45413 PreC      ┆ Long et al.  ┆ LR_MTP-073 ┆ 0         │
│ 05320444B       ┆ Yan et al.   ┆ YR_2466    ┆ 2         │
└─────────────────┴──────────────┴────────────┴───────────┘

## Convert GEX_MAT to patient-wised

In [28]:
gex_info = gex_mat.transpose(column_names='HGNC').insert_column(
    0, pl.Series('sample_id', gex_mat.columns[1:])
)
gex_info

shape: (125, 114)
┌─────────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id       ┆ BAIAP2L1 ┆ VCX3A    ┆ SV2B     ┆ … ┆ HIGD1B   ┆ CDO1     ┆ FGF13    ┆ CKAP5    │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str             ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 05320216B       ┆ 6.008745 ┆ 5.504085 ┆ 4.886019 ┆ … ┆ 4.38366  ┆ 5.058616 ┆ 5.243796 ┆ 7.43921  │
│ 28518_049E PreC ┆ 7.821183 ┆ 4.286877 ┆ 3.897034 ┆ … ┆ 5.79525  ┆ 3.938261 ┆ 6.333221 ┆ 6.723939 │
│ 16A             ┆ 5.576383 ┆ 5.827332 ┆ 5.048343 ┆ … ┆ 4.120395 ┆ 4.947229 ┆ 5.004979 ┆ 7.937973 │
│ 05420159C       ┆ 6.185604 ┆ 5.504085 ┆ 4.91511  ┆ … ┆ 4.350818 ┆ 5.105079 ┆ 5.525253 ┆ 7.00574  │
│ 05320093C       ┆ 5.82934  ┆ 5.504085 ┆ 4.965455 ┆ … ┆ 4.345875 ┆ 5.048585 ┆ 5.26147  ┆ 7.318584 │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 08626 PreC      ┆ 2.355895 ┆ 4.068271 ┆ 4.312354 ┆ … ┆ 3.789412 ┆ 3.941712 ┆ 2.980864 ┆ 6.396049 │
│ 05320119C       ┆ 6.134985 ┆ 5.518592 ┆ 4.887109 ┆ … ┆ 4.392305 ┆ 5.045629 ┆ 5.260428 ┆ 7.484392 │
│ 03660598B       ┆ 6.018943 ┆ 5.540102 ┆ 4.904131 ┆ … ┆ 4.334177 ┆ 5.050975 ┆ 5.253968 ┆ 7.597721 │
│ 45413 PreC      ┆ 2.944774 ┆ 4.467366 ┆ 4.267894 ┆ … ┆ 5.634533 ┆ 6.057534 ┆ 6.618716 ┆ 7.470223 │
│ 05320444B       ┆ 6.08192  ┆ 5.510745 ┆ 4.895287 ┆ … ┆ 4.357164 ┆ 5.086221 ┆ 5.270644 ┆ 7.988817 │
└─────────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [29]:
gex = sample_source.join(other=gex_info, on='sample_id')
gex

shape: (125, 117)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id  ┆ source     ┆ patientID  ┆ pfs_label ┆ … ┆ HIGD1B   ┆ CDO1     ┆ FGF13    ┆ CKAP5    │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str        ┆ i64       ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 05320216B  ┆ Yan et al. ┆ YR_2220    ┆ 0         ┆ … ┆ 4.38366  ┆ 5.058616 ┆ 5.243796 ┆ 7.43921  │
│ 28518_049E ┆ Long et    ┆ LR_MTP-034 ┆ 0         ┆ … ┆ 5.79525  ┆ 3.938261 ┆ 6.333221 ┆ 6.723939 │
│ PreC       ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 16A        ┆ Kwong et   ┆ KC_16      ┆ 1         ┆ … ┆ 4.120395 ┆ 4.947229 ┆ 5.004979 ┆ 7.937973 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 05420159C  ┆ Yan et al. ┆ YR_103001  ┆ 0         ┆ … ┆ 4.350818 ┆ 5.105079 ┆ 5.525253 ┆ 7.00574  │
│ 05320093C  ┆ Yan et al. ┆ YR_2096    ┆ 2         ┆ … ┆ 4.345875 ┆ 5.048585 ┆ 5.26147  ┆ 7.318584 │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 08626 PreC ┆ Long et    ┆ LR_WMD-033 ┆ 0         ┆ … ┆ 3.789412 ┆ 3.941712 ┆ 2.980864 ┆ 6.396049 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 05320119C  ┆ Yan et al. ┆ YR_2347    ┆ 0         ┆ … ┆ 4.392305 ┆ 5.045629 ┆ 5.260428 ┆ 7.484392 │
│ 03660598B  ┆ Yan et al. ┆ YR_3708    ┆ 2         ┆ … ┆ 4.334177 ┆ 5.050975 ┆ 5.253968 ┆ 7.597721 │
│ 45413 PreC ┆ Long et    ┆ LR_MTP-073 ┆ 0         ┆ … ┆ 5.634533 ┆ 6.057534 ┆ 6.618716 ┆ 7.470223 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 05320444B  ┆ Yan et al. ┆ YR_2466    ┆ 2         ┆ … ┆ 4.357164 ┆ 5.086221 ┆ 5.270644 ┆ 7.988817 │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

## Merge with Clinical dataset

In [30]:
clinical_gex = clinical.join(gex, on='patientID', how='inner')[:, 1:]
clinical_gex

shape: (125, 138)
┌───────────┬────────┬─────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ patientID ┆ sex    ┆ age ┆ AJCC_stage ┆ … ┆ HIGD1B   ┆ CDO1     ┆ FGF13    ┆ CKAP5    │
│ ---       ┆ ---    ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ str    ┆ i64 ┆ str        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════════╪════════╪═════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ YR_3053   ┆ male   ┆ 26  ┆ IV         ┆ … ┆ 4.321008 ┆ 5.059288 ┆ 5.314315 ┆ 7.235586 │
│ YR_3708   ┆ female ┆ 58  ┆ IV         ┆ … ┆ 4.334177 ┆ 5.050975 ┆ 5.253968 ┆ 7.597721 │
│ YR_3705   ┆ male   ┆ 45  ┆ IV         ┆ … ┆ 4.322683 ┆ 5.049908 ┆ 5.753911 ┆ 7.362745 │
│ YR_1106   ┆ male   ┆ 48  ┆ IIIC       ┆ … ┆ 4.339989 ┆ 5.099321 ┆ 5.272151 ┆ 7.003382 │
│ YR_1110   ┆ male   ┆ 33  ┆ IV         ┆ … ┆ 4.337075 ┆ 5.062783 ┆ 5.331733 ┆ 7.562456 │
│ …         ┆ …      ┆ …   ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ KC_19     ┆ male   ┆ 62  ┆ IV         ┆ … ┆ 4.300619 ┆ 4.994787 ┆ 5.011248 ┆ 6.884087 │
│ KC_22     ┆ male   ┆ 49  ┆ IV         ┆ … ┆ 4.178416 ┆ 4.956155 ┆ 5.66761  ┆ 8.215198 │
│ KC_24     ┆ female ┆ 68  ┆ IV         ┆ … ┆ 4.271833 ┆ 5.019694 ┆ 5.144334 ┆ 7.834134 │
│ KC_25     ┆ male   ┆ 72  ┆ IV         ┆ … ┆ 4.1981   ┆ 4.985225 ┆ 5.672139 ┆ 7.772773 │
│ KC_34     ┆ male   ┆ 33  ┆ IV         ┆ … ┆ 4.224212 ┆ 4.932832 ┆ 4.98145  ┆ 7.112893 │
└───────────┴────────┴─────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [31]:
clinical_gex.select(pl.all().null_count())

shape: (1, 138)
┌───────────┬─────┬─────┬────────────┬───┬────────┬──────┬───────┬───────┐
│ patientID ┆ sex ┆ age ┆ AJCC_stage ┆ … ┆ HIGD1B ┆ CDO1 ┆ FGF13 ┆ CKAP5 │
│ ---       ┆ --- ┆ --- ┆ ---        ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---   │
│ u32       ┆ u32 ┆ u32 ┆ u32        ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32   │
╞═══════════╪═════╪═════╪════════════╪═══╪════════╪══════╪═══════╪═══════╡
│ 0         ┆ 0   ┆ 0   ┆ 0          ┆ … ┆ 0      ┆ 0    ┆ 0     ┆ 0     │
└───────────┴─────┴─────┴────────────┴───┴────────┴──────┴───────┴───────┘

In [32]:
clinical_gex.write_csv(f"../dataset/created/clinical_gex.csv")