# 4. Merge Clinical and Corrected GEX_MAT

In [80]:
LIMMA_GENES = True

## Read datasets

In [81]:
import polars as pl

clinical = pl.read_csv(f"../dataset/created/clinical.csv")
clinical

shape: (415, 24)
┌─────┬───────────┬────────┬─────┬───┬───────┬───────┬───────┬───────┐
│     ┆ patientID ┆ sex    ┆ age ┆ … ┆ R558Q ┆ V600E ┆ V600K ┆ V600R │
│ --- ┆ ---       ┆ ---    ┆ --- ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ i64 ┆ str       ┆ str    ┆ i64 ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞═════╪═══════════╪════════╪═════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ 0   ┆ BS_000    ┆ male   ┆ 56  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 1   ┆ BS_001    ┆ male   ┆ 86  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 2   ┆ BS_002    ┆ female ┆ 47  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 3   ┆ BS_003    ┆ female ┆ 50  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 4   ┆ BS_004    ┆ female ┆ 47  ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ …   ┆ …         ┆ …      ┆ …   ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ 410 ┆ HL_Shi-40 ┆ male   ┆ 47  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 411 ┆ HL_Shi-41 ┆ male   ┆ 39  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 412 ┆ HL_Shi-42 ┆ male   ┆ 84  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 413 ┆ HL_Shi-43 ┆ female ┆ 41  ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ 414 ┆ HL_Shi-44 ┆ male   ┆ 83  ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
└─────┴───────────┴────────┴─────┴───┴───────┴───────┴───────┴───────┘

In [82]:
if LIMMA_GENES == True:
    gex_mat = pl.read_csv(f"../dataset/created/gex_mat_corrected_sig.csv")
    print(gex_mat)
else:
    gex_mat = pl.read_csv(f"../dataset/created/gex_mat_corrected.csv")
    # 1. Define which columns are the numeric data (samples)
    # We exclude 'HGNC' because it is a string/label
    sample_cols = [col for col in gex_mat.columns if col != 'HGNC']

    # 2. Compute variance for each row and add it as a new column
    # We use horizontal variance across the sample columns
    gex_with_var = gex_mat.with_columns(
        var = pl.concat_list(sample_cols).list.var()
    )

    # 3. Sort by variance descending and take the top 1000
    most_variable_genes = gex_with_var.sort("var", descending=True).head(1000)

    # 4. (Optional) Drop the 'var' column if you don't need it anymore
    gex_mat = most_variable_genes.drop("var")
    print(gex_mat)

shape: (122, 138)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ HGNC   ┆ 8755_035H  ┆ Pt1-baseli ┆ 08766     ┆ … ┆ 05420129C ┆ Pt2-basel ┆ 05320205B ┆ 05320100B │
│ ---    ┆ PreB       ┆ ne         ┆ PreC_014G ┆   ┆ ---       ┆ ine       ┆ ---       ┆ ---       │
│ str    ┆ ---        ┆ ---        ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│        ┆ f64        ┆ f64        ┆ f64       ┆   ┆           ┆ f64       ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ MAGEA4 ┆ 4.483408   ┆ 4.617514   ┆ 3.047771  ┆ … ┆ 4.332853  ┆ 4.636228  ┆ 4.329003  ┆ 5.337362  │
│ VCX3A  ┆ 10.136349  ┆ 5.529758   ┆ 4.977531  ┆ … ┆ 5.13136   ┆ 5.50946   ┆ 5.12214   ┆ 7.185458  │
│ SV2B   ┆ 4.867191   ┆ 4.884898   ┆ 3.475491  ┆ … ┆ 4.680057  ┆ 4.889576  ┆ 4.730536  ┆ 4.687803  │
│ MAGEA1 ┆ 8.881613   ┆ 4.765432   ┆ 3.278967  ┆ … ┆ 4.5101    ┆ 4.764475  ┆ 4.741909  ┆ 5.126223  │
│ VCX2   ┆ 8.81662    ┆ 5.637169   ┆ 3.935683  ┆ … ┆ 5.287292  ┆ 5.637169  ┆ 5.274799  ┆ 5.396627  │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ PPIH   ┆ 7.63735    ┆ 6.541229   ┆ 6.203982  ┆ … ┆ 6.761298  ┆ 6.551752  ┆ 6.859997  ┆ 6.967909  │
│ TFF3   ┆ 2.789269   ┆ 6.148049   ┆ 6.440745  ┆ … ┆ 5.017196  ┆ 4.56933   ┆ 5.030968  ┆ 5.015912  │
│ PBK    ┆ 3.810405   ┆ 5.847441   ┆ 7.838665  ┆ … ┆ 6.008446  ┆ 6.403943  ┆ 5.829609  ┆ 6.144011  │
│ FGF13  ┆ 4.723208   ┆ 5.741465   ┆ 3.365906  ┆ … ┆ 5.340631  ┆ 4.459718  ┆ 5.147697  ┆ 5.163701  │
│ EXOSC3 ┆ 5.856198   ┆ 6.665037   ┆ 6.999273  ┆ … ┆ 6.554751  ┆ 6.26609   ┆ 6.82253   ┆ 6.883759  │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [83]:
sample_source = pl.read_csv(f"../dataset/created/sample_source.csv")
sample_source

shape: (137, 4)
┌─────────────────┬──────────────┬────────────┬───────────┐
│ sample_id       ┆ source       ┆ patientID  ┆ pfs_label │
│ ---             ┆ ---          ┆ ---        ┆ ---       │
│ str             ┆ str          ┆ str        ┆ i64       │
╞═════════════════╪══════════════╪════════════╪═══════════╡
│ 8755_035H PreB  ┆ Rizos et al. ┆ RL_WMD-021 ┆ 1         │
│ Pt1-baseline    ┆ Hugo et al.  ┆ HL_Shi-15  ┆ 1         │
│ 08766 PreC_014G ┆ Long et al.  ┆ LR_WMD-022 ┆ 0         │
│ 05320220B       ┆ Yan et al.   ┆ YR_2148    ┆ 1         │
│ 03660598B       ┆ Yan et al.   ┆ YR_3708    ┆ 2         │
│ …               ┆ …            ┆ …          ┆ …         │
│ 05320216B       ┆ Yan et al.   ┆ YR_2220    ┆ 0         │
│ 05420129C       ┆ Yan et al.   ┆ YR_102011  ┆ 0         │
│ Pt2-baseline    ┆ Hugo et al.  ┆ HL_Shi-26  ┆ 0         │
│ 05320205B       ┆ Yan et al.   ┆ YR_2214    ┆ 2         │
│ 05320100B       ┆ Yan et al.   ┆ YR_2208    ┆ 0         │
└─────────────────┴──────────────┴────────────┴───────────┘

## Convert GEX_MAT to patient-wised

In [84]:
gex_info = gex_mat.transpose(column_names='HGNC').insert_column(
    0, pl.Series('sample_id', gex_mat.columns[1:])
)
gex_info

shape: (137, 123)
┌────────────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id      ┆ MAGEA4   ┆ VCX3A     ┆ SV2B     ┆ … ┆ TFF3     ┆ PBK      ┆ FGF13    ┆ EXOSC3   │
│ ---            ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str            ┆ f64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 8755_035H PreB ┆ 4.483408 ┆ 10.136349 ┆ 4.867191 ┆ … ┆ 2.789269 ┆ 3.810405 ┆ 4.723208 ┆ 5.856198 │
│ Pt1-baseline   ┆ 4.617514 ┆ 5.529758  ┆ 4.884898 ┆ … ┆ 6.148049 ┆ 5.847441 ┆ 5.741465 ┆ 6.665037 │
│ 08766          ┆ 3.047771 ┆ 4.977531  ┆ 3.475491 ┆ … ┆ 6.440745 ┆ 7.838665 ┆ 3.365906 ┆ 6.999273 │
│ PreC_014G      ┆          ┆           ┆          ┆   ┆          ┆          ┆          ┆          │
│ 05320220B      ┆ 4.329003 ┆ 5.12214   ┆ 4.681457 ┆ … ┆ 5.021874 ┆ 6.107214 ┆ 5.12339  ┆ 6.70964  │
│ 03660598B      ┆ 6.570555 ┆ 5.158157  ┆ 4.697329 ┆ … ┆ 5.049185 ┆ 6.070983 ┆ 5.128801 ┆ 6.472128 │
│ …              ┆ …        ┆ …         ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 05320216B      ┆ 4.329003 ┆ 5.12214   ┆ 4.679216 ┆ … ┆ 5.021538 ┆ 6.54504  ┆ 5.118629 ┆ 7.086777 │
│ 05420129C      ┆ 4.332853 ┆ 5.13136   ┆ 4.680057 ┆ … ┆ 5.017196 ┆ 6.008446 ┆ 5.340631 ┆ 6.554751 │
│ Pt2-baseline   ┆ 4.636228 ┆ 5.50946   ┆ 4.889576 ┆ … ┆ 4.56933  ┆ 6.403943 ┆ 4.459718 ┆ 6.26609  │
│ 05320205B      ┆ 4.329003 ┆ 5.12214   ┆ 4.730536 ┆ … ┆ 5.030968 ┆ 5.829609 ┆ 5.147697 ┆ 6.82253  │
│ 05320100B      ┆ 5.337362 ┆ 7.185458  ┆ 4.687803 ┆ … ┆ 5.015912 ┆ 6.144011 ┆ 5.163701 ┆ 6.883759 │
└────────────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [85]:
gex = sample_source.join(other=gex_info, on='sample_id')
gex

shape: (137, 126)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id  ┆ source     ┆ patientID  ┆ pfs_label ┆ … ┆ TFF3     ┆ PBK      ┆ FGF13    ┆ EXOSC3   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str        ┆ i64       ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 8755_035H  ┆ Rizos et   ┆ RL_WMD-021 ┆ 1         ┆ … ┆ 2.789269 ┆ 3.810405 ┆ 4.723208 ┆ 5.856198 │
│ PreB       ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ Pt1-baseli ┆ Hugo et    ┆ HL_Shi-15  ┆ 1         ┆ … ┆ 6.148049 ┆ 5.847441 ┆ 5.741465 ┆ 6.665037 │
│ ne         ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 08766      ┆ Long et    ┆ LR_WMD-022 ┆ 0         ┆ … ┆ 6.440745 ┆ 7.838665 ┆ 3.365906 ┆ 6.999273 │
│ PreC_014G  ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 05320220B  ┆ Yan et al. ┆ YR_2148    ┆ 1         ┆ … ┆ 5.021874 ┆ 6.107214 ┆ 5.12339  ┆ 6.70964  │
│ 03660598B  ┆ Yan et al. ┆ YR_3708    ┆ 2         ┆ … ┆ 5.049185 ┆ 6.070983 ┆ 5.128801 ┆ 6.472128 │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 05320216B  ┆ Yan et al. ┆ YR_2220    ┆ 0         ┆ … ┆ 5.021538 ┆ 6.54504  ┆ 5.118629 ┆ 7.086777 │
│ 05420129C  ┆ Yan et al. ┆ YR_102011  ┆ 0         ┆ … ┆ 5.017196 ┆ 6.008446 ┆ 5.340631 ┆ 6.554751 │
│ Pt2-baseli ┆ Hugo et    ┆ HL_Shi-26  ┆ 0         ┆ … ┆ 4.56933  ┆ 6.403943 ┆ 4.459718 ┆ 6.26609  │
│ ne         ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 05320205B  ┆ Yan et al. ┆ YR_2214    ┆ 2         ┆ … ┆ 5.030968 ┆ 5.829609 ┆ 5.147697 ┆ 6.82253  │
│ 05320100B  ┆ Yan et al. ┆ YR_2208    ┆ 0         ┆ … ┆ 5.015912 ┆ 6.144011 ┆ 5.163701 ┆ 6.883759 │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

## Merge with Clinical dataset

In [86]:
clinical_gex = clinical.join(gex, on='patientID', how='inner')[:, 1:]
clinical_gex

shape: (137, 148)
┌───────────┬────────┬─────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ patientID ┆ sex    ┆ age ┆ AJCC_stage ┆ … ┆ TFF3     ┆ PBK      ┆ FGF13    ┆ EXOSC3   │
│ ---       ┆ ---    ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ str    ┆ i64 ┆ str        ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════════╪════════╪═════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ YR_3053   ┆ male   ┆ 26  ┆ IV         ┆ … ┆ 5.003677 ┆ 5.890783 ┆ 5.189148 ┆ 6.328    │
│ YR_3708   ┆ female ┆ 58  ┆ IV         ┆ … ┆ 5.049185 ┆ 6.070983 ┆ 5.128801 ┆ 6.472128 │
│ YR_3705   ┆ male   ┆ 45  ┆ IV         ┆ … ┆ 5.008392 ┆ 5.894473 ┆ 5.628744 ┆ 6.725773 │
│ YR_1106   ┆ male   ┆ 48  ┆ IIIC       ┆ … ┆ 5.060871 ┆ 5.74085  ┆ 5.146984 ┆ 6.30193  │
│ YR_1110   ┆ male   ┆ 33  ┆ IV         ┆ … ┆ 5.064195 ┆ 5.65068  ┆ 5.206566 ┆ 6.41538  │
│ …         ┆ …      ┆ …   ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ HL_Shi-35 ┆ male   ┆ 61  ┆ IV         ┆ … ┆ 4.545481 ┆ 6.26327  ┆ 4.477394 ┆ 6.552303 │
│ HL_Shi-37 ┆ male   ┆ 65  ┆ IV         ┆ … ┆ 4.677891 ┆ 5.256349 ┆ 4.78294  ┆ 6.214688 │
│ HL_Shi-38 ┆ male   ┆ 51  ┆ IV         ┆ … ┆ 4.520856 ┆ 5.695232 ┆ 5.693097 ┆ 6.958281 │
│ HL_Shi-43 ┆ female ┆ 41  ┆ IV         ┆ … ┆ 4.652919 ┆ 5.917283 ┆ 4.422212 ┆ 6.718769 │
│ HL_Shi-44 ┆ male   ┆ 83  ┆ IV         ┆ … ┆ 4.538628 ┆ 6.134197 ┆ 5.272464 ┆ 6.623181 │
└───────────┴────────┴─────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [87]:
clinical_gex.write_csv(f"../dataset/created/clinical_gex.csv")