In [2]:
import polars as pl

DATASET = 'gex_pre'

gex_mat = pl.read_csv(f"../dataset/created/gex_mat_corrected/{DATASET}.csv")
gex_mat

shape: (13_192, 164)
┌──────────┬─────────────┬───────────┬─────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ HGNC     ┆ 28067_028D  ┆ 05320459B ┆ 8755_072F   ┆ … ┆ LMSAM_14 ┆ LMSAM_26 ┆ LMSAM_20 ┆ LMSAM_27 │
│ ---      ┆ PreB        ┆ ---       ┆ PreB        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str      ┆ ---         ┆ f64       ┆ ---         ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
│          ┆ f64         ┆           ┆ f64         ┆   ┆          ┆          ┆          ┆          │
╞══════════╪═════════════╪═══════════╪═════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ CEBPZ    ┆ 6.914581    ┆ 7.421282  ┆ 6.137618    ┆ … ┆ 7.075648 ┆ 7.075648 ┆ 7.075648 ┆ 7.075648 │
│ SLC38A5  ┆ 4.331833    ┆ 4.762737  ┆ 5.345661    ┆ … ┆ 4.870727 ┆ 4.870727 ┆ 4.870727 ┆ 4.870727 │
│ GJA4     ┆ 4.259052    ┆ 5.168505  ┆ 6.10902     ┆ … ┆ 5.224361 ┆ 5.224361 ┆ 5.224361 ┆ 5.224361 │
│ TUBGCP2  ┆ 5.811283    ┆ 6.478005  ┆ 6.506419    ┆ … ┆ 6.35448  ┆ 6.35448  ┆ 6.35448  ┆ 6.35448  │
│ FMO6P    ┆ 4.742731    ┆ 4.661665  ┆ 4.56619     ┆ … ┆ 4.673781 ┆ 4.673781 ┆ 4.673781 ┆ 4.673781 │
│ …        ┆ …           ┆ …         ┆ …           ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ FBN2     ┆ 5.785345    ┆ 4.940437  ┆ 4.833427    ┆ … ┆ 5.180638 ┆ 5.180638 ┆ 5.180638 ┆ 5.180638 │
│ KIAA1586 ┆ 5.228025    ┆ 5.01107   ┆ 4.351472    ┆ … ┆ 4.824449 ┆ 4.824449 ┆ 4.824449 ┆ 4.824449 │
│ CLIC5    ┆ 3.361714    ┆ 3.988136  ┆ 4.736087    ┆ … ┆ 3.998221 ┆ 3.998221 ┆ 3.998221 ┆ 3.998221 │
│ HAUS6    ┆ 5.481637    ┆ 4.584268  ┆ 4.613592    ┆ … ┆ 4.602617 ┆ 4.602617 ┆ 4.602617 ┆ 4.602617 │
│ MIRLET7D ┆ 5.074056    ┆ 5.42861   ┆ 3.482295    ┆ … ┆ 4.590374 ┆ 4.590374 ┆ 4.590374 ┆ 4.590374 │
└──────────┴─────────────┴───────────┴─────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [3]:
sample_source = pl.read_csv(f"../dataset/created/sample_source/{DATASET}.csv")
sample_source

shape: (163, 4)
┌─────────────────┬────────────────┬────────────┬─────────────┐
│ sample_id       ┆ source         ┆ patientID  ┆ Method      │
│ ---             ┆ ---            ┆ ---        ┆ ---         │
│ str             ┆ str            ┆ str        ┆ str         │
╞═════════════════╪════════════════╪════════════╪═════════════╡
│ 28067_028D PreB ┆ Rizos et al.   ┆ RL_WMD-007 ┆ micro-array │
│ 05320459B       ┆ Yan et al.     ┆ YR_2417    ┆ RNA-seq     │
│ 8755_072F PreB  ┆ Rizos et al.   ┆ RL_WMD-021 ┆ micro-array │
│ 27473_010F PreB ┆ Rizos et al.   ┆ RL_WMD-039 ┆ micro-array │
│ 05420169C       ┆ Yan et al.     ┆ YR_104002  ┆ RNA-seq     │
│ …               ┆ …              ┆ …          ┆ …           │
│ LMSAM_6         ┆ Louveau et al. ┆ LM_6       ┆ qPCR        │
│ LMSAM_14        ┆ Louveau et al. ┆ LM_14      ┆ qPCR        │
│ LMSAM_26        ┆ Louveau et al. ┆ LM_26      ┆ qPCR        │
│ LMSAM_20        ┆ Louveau et al. ┆ LM_20      ┆ qPCR        │
│ LMSAM_27        ┆ Louveau et al. ┆ LM_27      ┆ qPCR        │
└─────────────────┴────────────────┴────────────┴─────────────┘

In [12]:
gex_info = gex_mat.transpose(column_names='HGNC').insert_column(
    0, pl.Series('sample_id', gex_mat.columns[1:])
)
gex_info

shape: (163, 13_193)
┌─────────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id       ┆ CEBPZ    ┆ SLC38A5  ┆ GJA4     ┆ … ┆ KIAA1586 ┆ CLIC5    ┆ HAUS6    ┆ MIRLET7D │
│ ---             ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str             ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 28067_028D PreB ┆ 6.914581 ┆ 4.331833 ┆ 4.259052 ┆ … ┆ 5.228025 ┆ 3.361714 ┆ 5.481637 ┆ 5.074056 │
│ 05320459B       ┆ 7.421282 ┆ 4.762737 ┆ 5.168505 ┆ … ┆ 5.01107  ┆ 3.988136 ┆ 4.584268 ┆ 5.42861  │
│ 8755_072F PreB  ┆ 6.137618 ┆ 5.345661 ┆ 6.10902  ┆ … ┆ 4.351472 ┆ 4.736087 ┆ 4.613592 ┆ 3.482295 │
│ 27473_010F PreB ┆ 5.425898 ┆ 5.142804 ┆ 5.480295 ┆ … ┆ 3.931674 ┆ 4.051061 ┆ 3.77515  ┆ 4.080538 │
│ 05420169C       ┆ 6.714453 ┆ 4.804508 ┆ 5.458675 ┆ … ┆ 4.567486 ┆ 3.997787 ┆ 4.500672 ┆ 5.267851 │
│ …               ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ LMSAM_6         ┆ 7.075648 ┆ 4.870727 ┆ 5.224361 ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│ LMSAM_14        ┆ 7.075648 ┆ 4.870727 ┆ 5.224361 ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│ LMSAM_26        ┆ 7.075648 ┆ 4.870727 ┆ 5.224361 ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│ LMSAM_20        ┆ 7.075648 ┆ 4.870727 ┆ 5.224361 ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│ LMSAM_27        ┆ 7.075648 ┆ 4.870727 ┆ 5.224361 ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
└─────────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [15]:
gex_complete = sample_source.join(other=gex_info, on='sample_id')
gex_complete

shape: (163, 13_196)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id  ┆ source     ┆ patientID  ┆ Method    ┆ … ┆ KIAA1586 ┆ CLIC5    ┆ HAUS6    ┆ MIRLET7D │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 28067_028D ┆ Rizos et   ┆ RL_WMD-007 ┆ micro-arr ┆ … ┆ 5.228025 ┆ 3.361714 ┆ 5.481637 ┆ 5.074056 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05320459B  ┆ Yan et al. ┆ YR_2417    ┆ RNA-seq   ┆ … ┆ 5.01107  ┆ 3.988136 ┆ 4.584268 ┆ 5.42861  │
│ 8755_072F  ┆ Rizos et   ┆ RL_WMD-021 ┆ micro-arr ┆ … ┆ 4.351472 ┆ 4.736087 ┆ 4.613592 ┆ 3.482295 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 27473_010F ┆ Rizos et   ┆ RL_WMD-039 ┆ micro-arr ┆ … ┆ 3.931674 ┆ 4.051061 ┆ 3.77515  ┆ 4.080538 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05420169C  ┆ Yan et al. ┆ YR_104002  ┆ RNA-seq   ┆ … ┆ 4.567486 ┆ 3.997787 ┆ 4.500672 ┆ 5.267851 │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ LMSAM_6    ┆ Louveau et ┆ LM_6       ┆ qPCR      ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ LMSAM_14   ┆ Louveau et ┆ LM_14      ┆ qPCR      ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ LMSAM_26   ┆ Louveau et ┆ LM_26      ┆ qPCR      ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ LMSAM_20   ┆ Louveau et ┆ LM_20      ┆ qPCR      ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ LMSAM_27   ┆ Louveau et ┆ LM_27      ┆ qPCR      ┆ … ┆ 4.824449 ┆ 3.998221 ┆ 4.602617 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [17]:
gex_complete = gex_complete.remove(pl.col('source') == 'Louveau et al.')
gex_complete

shape: (143, 13_196)
┌────────────┬────────────┬────────────┬───────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sample_id  ┆ source     ┆ patientID  ┆ Method    ┆ … ┆ KIAA1586 ┆ CLIC5    ┆ HAUS6    ┆ MIRLET7D │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str        ┆ str        ┆ str        ┆ str       ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════════╪════════════╪════════════╪═══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 28067_028D ┆ Rizos et   ┆ RL_WMD-007 ┆ micro-arr ┆ … ┆ 5.228025 ┆ 3.361714 ┆ 5.481637 ┆ 5.074056 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05320459B  ┆ Yan et al. ┆ YR_2417    ┆ RNA-seq   ┆ … ┆ 5.01107  ┆ 3.988136 ┆ 4.584268 ┆ 5.42861  │
│ 8755_072F  ┆ Rizos et   ┆ RL_WMD-021 ┆ micro-arr ┆ … ┆ 4.351472 ┆ 4.736087 ┆ 4.613592 ┆ 3.482295 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 27473_010F ┆ Rizos et   ┆ RL_WMD-039 ┆ micro-arr ┆ … ┆ 3.931674 ┆ 4.051061 ┆ 3.77515  ┆ 4.080538 │
│ PreB       ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05420169C  ┆ Yan et al. ┆ YR_104002  ┆ RNA-seq   ┆ … ┆ 4.567486 ┆ 3.997787 ┆ 4.500672 ┆ 5.267851 │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 05320410C  ┆ Yan et al. ┆ YR_2390    ┆ RNA-seq   ┆ … ┆ 4.975712 ┆ 4.035869 ┆ 4.538475 ┆ 3.985953 │
│ 16A        ┆ Kwong et   ┆ KC_16      ┆ RNA-seq   ┆ … ┆ 4.915265 ┆ 3.984482 ┆ 4.688729 ┆ 4.590374 │
│            ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
│ 08766      ┆ Long et    ┆ LR_WMD-022 ┆ micro-arr ┆ … ┆ 5.870401 ┆ 3.98803  ┆ 5.339926 ┆ 4.355084 │
│ PreC_014G  ┆ al.        ┆            ┆ ay        ┆   ┆          ┆          ┆          ┆          │
│ 05320328B  ┆ Yan et al. ┆ YR_2472    ┆ RNA-seq   ┆ … ┆ 4.895777 ┆ 3.980708 ┆ 4.713952 ┆ 4.035995 │
│ Pt10-basel ┆ Hugo et    ┆ HL_Shi-37  ┆ RNA-seq   ┆ … ┆ 4.567853 ┆ 3.97117  ┆ 4.282064 ┆ 4.590374 │
│ ine        ┆ al.        ┆            ┆           ┆   ┆          ┆          ┆          ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [18]:
gex_complete.write_csv(f"../dataset/created/gex_corrected/{DATASET}.csv")