## Gene Expression (GEx)

In [90]:
import polars as pl

In [91]:
gex_df = pl.read_csv("../dataset/original/gene_expressions.csv")
gex_df

shape: (8_641_391, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ creation_d ┆ patientID ┆ sample_id ┆ … ┆ descripti ┆ value     ┆ temporali ┆ source    │
│ ---     ┆ atetime    ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ty        ┆ ---       │
│ i64     ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│         ┆ str        ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 7.60798   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03260      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 2       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 16.095204 ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03285      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 3       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 4.1515    ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03298      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 4       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 1.199885  ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03312      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 5       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 5.47246   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03324      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8641387 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 0.019542  ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29746      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641388 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 4.04421   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29757      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641389 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 85.7967   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29768      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641390 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 5.759167  ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29778      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8641391 ┆ 2025-04-24 ┆ HL_Shi-40 ┆ Pt21-DP2  ┆ … ┆ null      ┆ 8.64874   ┆ progressi ┆ doi:10.10 │
│         ┆ 00:42:16.6 ┆           ┆           ┆   ┆           ┆           ┆ on        ┆ 16/j.cell │
│         ┆ 29788      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [92]:
# gex_df.group_by('source').agg(
#     pl.col('value').min().alias('min'),
#     pl.col('value').max().alias('max'),
#     pl.col('value').mean().alias('mean'),
#     pl.col('value').median().alias('median'),
# ).sort('source')

In [93]:
gex_df.select(pl.all().null_count())

shape: (1, 10)
┌─────┬───────────────────┬───────────┬───────────┬───┬─────────────┬───────┬─────────────┬────────┐
│ id  ┆ creation_datetime ┆ patientID ┆ sample_id ┆ … ┆ description ┆ value ┆ temporality ┆ source │
│ --- ┆ ---               ┆ ---       ┆ ---       ┆   ┆ ---         ┆ ---   ┆ ---         ┆ ---    │
│ u32 ┆ u32               ┆ u32       ┆ u32       ┆   ┆ u32         ┆ u32   ┆ u32         ┆ u32    │
╞═════╪═══════════════════╪═══════════╪═══════════╪═══╪═════════════╪═══════╪═════════════╪════════╡
│ 0   ┆ 0                 ┆ 92181     ┆ 0         ┆ … ┆ 4568231     ┆ 0     ┆ 95655       ┆ 0      │
└─────┴───────────────────┴───────────┴───────────┴───┴─────────────┴───────┴─────────────┴────────┘

In [94]:
gex_df = gex_df.filter(pl.col('temporality') == 'pre treatment')
gex_df

shape: (4_466_466, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ creation_d ┆ patientID ┆ sample_id ┆ … ┆ descripti ┆ value     ┆ temporali ┆ source    │
│ ---     ┆ atetime    ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ty        ┆ ---       │
│ i64     ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│         ┆ str        ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 7.60798   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03260      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 2       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 16.095204 ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03285      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 3       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 4.1515    ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03298      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 4       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 1.199885  ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03312      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ 5       ┆ 2025-04-23 ┆ LM_1      ┆ LMSAM_1   ┆ … ┆ null      ┆ 5.47246   ┆ pre       ┆ doi:10.33 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 90/cancer │
│         ┆ 03324      ┆           ┆           ┆   ┆           ┆           ┆           ┆ s11081203 │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8565583 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 0.0625681 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10407      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565584 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 5.74608   ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10417      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565585 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 45.907933 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10428      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565586 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 3.015137  ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10438      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565587 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 10.684633 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10449      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [95]:
# Hugo et al., Kwong et al. and Yan et al. studies because they used a similar method 
# (mRNA expression profiling performed with Illumina HiSeq 2000)
source_rna_seq = ['doi:10.1016/j.cell.2015.07.061', 'doi:10.1158/1078-0432.CCR-18-0720', 'doi:10.1172/JCI78954DS1']

gex_df = gex_df.filter(pl.col('source').is_in(source_rna_seq))
gex_df

shape: (2_961_950, 10)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ creation_d ┆ patientID ┆ sample_id ┆ … ┆ descripti ┆ value     ┆ temporali ┆ source    │
│ ---     ┆ atetime    ┆ ---       ┆ ---       ┆   ┆ on        ┆ ---       ┆ ty        ┆ ---       │
│ i64     ┆ ---        ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│         ┆ str        ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 581     ┆ 2025-04-23 ┆ null      ┆ 03660196C ┆ … ┆ null      ┆ 6.898152  ┆ pre       ┆ doi:10.11 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 58/1078-0 │
│         ┆ 53695      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 432.CCR-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8-0…      │
│ 582     ┆ 2025-04-23 ┆ null      ┆ 03660196C ┆ … ┆ null      ┆ 0.068518  ┆ pre       ┆ doi:10.11 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 58/1078-0 │
│         ┆ 53710      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 432.CCR-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8-0…      │
│ 583     ┆ 2025-04-23 ┆ null      ┆ 03660196C ┆ … ┆ null      ┆ 30.686816 ┆ pre       ┆ doi:10.11 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 58/1078-0 │
│         ┆ 53722      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 432.CCR-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8-0…      │
│ 584     ┆ 2025-04-23 ┆ null      ┆ 03660196C ┆ … ┆ null      ┆ 0.180316  ┆ pre       ┆ doi:10.11 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 58/1078-0 │
│         ┆ 53733      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 432.CCR-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8-0…      │
│ 585     ┆ 2025-04-23 ┆ null      ┆ 03660196C ┆ … ┆ null      ┆ 17.434889 ┆ pre       ┆ doi:10.11 │
│         ┆ 23:02:05.5 ┆           ┆           ┆   ┆           ┆           ┆ treatment ┆ 58/1078-0 │
│         ┆ 53745      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 432.CCR-1 │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8-0…      │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8565583 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 0.0625681 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10407      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565584 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 5.74608   ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10417      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565585 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 45.907933 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10428      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565586 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 3.015137  ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10438      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
│ 8565587 ┆ 2025-04-24 ┆ HL_Shi-43 ┆ Pt17-base ┆ … ┆ null      ┆ 10.684633 ┆ pre       ┆ doi:10.10 │
│         ┆ 00:42:09.7 ┆           ┆ line      ┆   ┆           ┆           ┆ treatment ┆ 16/j.cell │
│         ┆ 10449      ┆           ┆           ┆   ┆           ┆           ┆           ┆ .2015.07. │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ 061       │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [96]:
gex_df = gex_df.drop(['id', 'creation_datetime', 'GeneID', 'description', 'temporality'])
gex_df.select(pl.all().null_count())

shape: (1, 5)
┌───────────┬───────────┬────────┬───────┬────────┐
│ patientID ┆ sample_id ┆ HGNC   ┆ value ┆ source │
│ ---       ┆ ---       ┆ ---    ┆ ---   ┆ ---    │
│ u32       ┆ u32       ┆ u32    ┆ u32   ┆ u32    │
╞═══════════╪═══════════╪════════╪═══════╪════════╡
│ 92181     ┆ 0         ┆ 207000 ┆ 0     ┆ 0      │
└───────────┴───────────┴────────┴───────┴────────┘

In [97]:
gex_df = gex_df.drop_nulls(subset=['patientID', 'HGNC'])
gex_df.select(pl.all().null_count())

shape: (1, 5)
┌───────────┬───────────┬──────┬───────┬────────┐
│ patientID ┆ sample_id ┆ HGNC ┆ value ┆ source │
│ ---       ┆ ---       ┆ ---  ┆ ---   ┆ ---    │
│ u32       ┆ u32       ┆ u32  ┆ u32   ┆ u32    │
╞═══════════╪═══════════╪══════╪═══════╪════════╡
│ 0         ┆ 0         ┆ 0    ┆ 0     ┆ 0      │
└───────────┴───────────┴──────┴───────┴────────┘

In [98]:
gex_df

shape: (2_671_394, 5)
┌───────────┬───────────────┬─────────┬───────────┬─────────────────────────────────┐
│ patientID ┆ sample_id     ┆ HGNC    ┆ value     ┆ source                          │
│ ---       ┆ ---           ┆ ---     ┆ ---       ┆ ---                             │
│ str       ┆ str           ┆ str     ┆ f64       ┆ str                             │
╞═══════════╪═══════════════╪═════════╪═══════════╪═════════════════════════════════╡
│ YR_5306   ┆ 03660445B     ┆ NAT2    ┆ 0.0       ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ YR_5306   ┆ 03660445B     ┆ ADA     ┆ 26.233973 ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ YR_5306   ┆ 03660445B     ┆ CDH2    ┆ 1.138609  ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ YR_5306   ┆ 03660445B     ┆ AKT3    ┆ 12.692677 ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ YR_5306   ┆ 03660445B     ┆ GAGE12F ┆ 0.0       ┆ doi:10.1158/1078-0432.CCR-18-0… │
│ …         ┆ …             ┆ …       ┆ …         ┆ …                               │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11A  ┆ 0.0625681 ┆ doi:10.1016/j.cell.2015.07.061  │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11B  ┆ 5.74608   ┆ doi:10.1016/j.cell.2015.07.061  │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYX     ┆ 45.907933 ┆ doi:10.1016/j.cell.2015.07.061  │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZEF1   ┆ 3.015137  ┆ doi:10.1016/j.cell.2015.07.061  │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZZ3    ┆ 10.684633 ┆ doi:10.1016/j.cell.2015.07.061  │
└───────────┴───────────────┴─────────┴───────────┴─────────────────────────────────┘

In [99]:
source_map = {
    'doi:10.1016/j.cell.2015.07.061': 'Hugo et al.',
    'doi:10.1172/JCI78954DS1': 'Kwong et al.',
    'doi:10.1158/1078-0432.CCR-18-0720': 'Yan et al.'
}

gex_df = gex_df.with_columns(pl.col('source').replace(source_map))
gex_df

shape: (2_671_394, 5)
┌───────────┬───────────────┬─────────┬───────────┬─────────────┐
│ patientID ┆ sample_id     ┆ HGNC    ┆ value     ┆ source      │
│ ---       ┆ ---           ┆ ---     ┆ ---       ┆ ---         │
│ str       ┆ str           ┆ str     ┆ f64       ┆ str         │
╞═══════════╪═══════════════╪═════════╪═══════════╪═════════════╡
│ YR_5306   ┆ 03660445B     ┆ NAT2    ┆ 0.0       ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ ADA     ┆ 26.233973 ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ CDH2    ┆ 1.138609  ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ AKT3    ┆ 12.692677 ┆ Yan et al.  │
│ YR_5306   ┆ 03660445B     ┆ GAGE12F ┆ 0.0       ┆ Yan et al.  │
│ …         ┆ …             ┆ …       ┆ …         ┆ …           │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11A  ┆ 0.0625681 ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYG11B  ┆ 5.74608   ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZYX     ┆ 45.907933 ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZEF1   ┆ 3.015137  ┆ Hugo et al. │
│ HL_Shi-43 ┆ Pt17-baseline ┆ ZZZ3    ┆ 10.684633 ┆ Hugo et al. │
└───────────┴───────────────┴─────────┴───────────┴─────────────┘

In [100]:
# gex_df.write_csv('../dataset/created/gex_rna_seq.csv')