In [1]:
import polars as pl

# Patient (Clinical)

In [10]:
patient_df = pl.read_csv("dataset/clinical.csv")
patient_df

shape: (417, 23)
┌─────┬──────────────┬───────────┬──────────────┬───┬──────────┬──────────┬──────────┬─────────────┐
│ id  ┆ creation_dat ┆ patientID ┆ original_pat ┆ … ┆ CNA_data ┆ SNV_data ┆ GEX_data ┆ source      │
│ --- ┆ etime        ┆ ---       ┆ ientID       ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---         │
│ i64 ┆ ---          ┆ str       ┆ ---          ┆   ┆ str      ┆ str      ┆ str      ┆ str         │
│     ┆ str          ┆           ┆ str          ┆   ┆          ┆          ┆          ┆             │
╞═════╪══════════════╪═══════════╪══════════════╪═══╪══════════╪══════════╪══════════╪═════════════╡
│ 1   ┆ 2025-04-23   ┆ BS_000    ┆ 0            ┆ … ┆ no       ┆ yes      ┆ no       ┆ doi:10.3390 │
│     ┆ 22:54:49.773 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /cancers120 │
│     ┆ 923          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 82224       │
│ 2   ┆ 2025-04-23   ┆ BS_001    ┆ 1            ┆ … ┆ no       ┆ yes      ┆ no       ┆ doi:10.3390 │
│     ┆ 22:54:49.802 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /cancers120 │
│     ┆ 003          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 82224       │
│ 3   ┆ 2025-04-23   ┆ BS_002    ┆ 2            ┆ … ┆ no       ┆ yes      ┆ no       ┆ doi:10.3390 │
│     ┆ 22:54:49.807 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /cancers120 │
│     ┆ 526          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 82224       │
│ 4   ┆ 2025-04-23   ┆ BS_003    ┆ 3            ┆ … ┆ no       ┆ yes      ┆ no       ┆ doi:10.3390 │
│     ┆ 22:54:49.813 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /cancers120 │
│     ┆ 005          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 82224       │
│ 5   ┆ 2025-04-23   ┆ BS_004    ┆ 4            ┆ … ┆ no       ┆ yes      ┆ no       ┆ doi:10.3390 │
│     ┆ 22:54:49.818 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /cancers120 │
│     ┆ 403          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 82224       │
│ …   ┆ …            ┆ …         ┆ …            ┆ … ┆ …        ┆ …        ┆ …        ┆ …           │
│ 413 ┆ 2025-04-23   ┆ HL_40     ┆ Shi-40       ┆ … ┆ no       ┆ no       ┆ yes      ┆ doi:10.1016 │
│     ┆ 22:54:53.873 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /j.cell.201 │
│     ┆ 737          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 5.07.061    │
│ 414 ┆ 2025-04-23   ┆ HL_41     ┆ Shi-41       ┆ … ┆ no       ┆ no       ┆ yes      ┆ doi:10.1016 │
│     ┆ 22:54:53.880 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /j.cell.201 │
│     ┆ 906          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 5.07.061    │
│ 415 ┆ 2025-04-23   ┆ HL_42     ┆ Shi-42       ┆ … ┆ no       ┆ no       ┆ yes      ┆ doi:10.1016 │
│     ┆ 22:54:53.887 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /j.cell.201 │
│     ┆ 897          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 5.07.061    │
│ 416 ┆ 2025-04-23   ┆ HL_43     ┆ Shi-43       ┆ … ┆ no       ┆ no       ┆ yes      ┆ doi:10.1016 │
│     ┆ 22:54:53.895 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /j.cell.201 │
│     ┆ 830          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 5.07.061    │
│ 417 ┆ 2025-04-23   ┆ HL_44     ┆ Shi-44       ┆ … ┆ no       ┆ no       ┆ yes      ┆ doi:10.1016 │
│     ┆ 22:54:53.912 ┆           ┆              ┆   ┆          ┆          ┆          ┆ /j.cell.201 │
│     ┆ 355          ┆           ┆              ┆   ┆          ┆          ┆          ┆ 5.07.061    │
└─────┴──────────────┴───────────┴──────────────┴───┴──────────┴──────────┴──────────┴─────────────┘

In [11]:
def count_unique_value_per_class(df):
    for feat in df.columns:
        print(f'{df[feat].value_counts()}\n')
        
count_unique_value_per_class(patient_df)

shape: (417, 2)
┌─────┬───────┐
│ id  ┆ count │
│ --- ┆ ---   │
│ i64 ┆ u32   │
╞═════╪═══════╡
│ 315 ┆ 1     │
│ 146 ┆ 1     │
│ 387 ┆ 1     │
│ 338 ┆ 1     │
│ 83  ┆ 1     │
│ …   ┆ …     │
│ 212 ┆ 1     │
│ 134 ┆ 1     │
│ 248 ┆ 1     │
│ 345 ┆ 1     │
│ 357 ┆ 1     │
└─────┴───────┘

shape: (417, 2)
┌────────────────────────────┬───────┐
│ creation_datetime          ┆ count │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ 2025-04-23 22:54:50.015578 ┆ 1     │
│ 2025-04-23 22:54:50.004136 ┆ 1     │
│ 2025-04-23 22:54:50.085518 ┆ 1     │
│ 2025-04-23 22:54:51.724939 ┆ 1     │
│ 2025-04-23 22:54:51.413574 ┆ 1     │
│ …                          ┆ …     │
│ 2025-04-23 22:54:49.839645 ┆ 1     │
│ 2025-04-23 22:54:53.479556 ┆ 1     │
│ 2025-04-23 22:54:50.280493 ┆ 1     │
│ 2025-04-23 22:54:52.521349 ┆ 1     │
│ 2025-04-23 22:54:52.659832 ┆ 1     │
└────────────────────────────┴───────┘

shape: (417, 2)
┌────────────┬───────┐
│ patientID  ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ CS_MT004   ┆ 1     │
│ CS_VT022   ┆ 1     │
│ HL_13      ┆ 1     │
│ BS_010     ┆ 1     │
│ YR_8902    ┆ 1     │
│ …          ┆ …     │
│ HL_32      ┆ 1     │
│ RL_WMD-006 ┆ 1     │
│ RL_MTP-001 ┆ 1     │
│ YR_2210    ┆ 1     │
│ VS_Pat_55  ┆ 1     │
└────────────┴───────┘

shape: (371, 2)
┌────────────────────┬───────┐
│ original_patientID ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ 2484               ┆ 1     │
│ 2194               ┆ 1     │
│ 23                 ┆ 2     │
│ 2492               ┆ 1     │
│ Shi-40             ┆ 1     │
│ …                  ┆ …     │
│ 2213               ┆ 1     │
│ Shi-37             ┆ 1     │
│ 12                 ┆ 2     │
│ 42                 ┆ 1     │
│ 2417               ┆ 1     │
└────────────────────┴───────┘

shape: (2, 2)
┌────────┬───────┐
│ sex    ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ female ┆ 174   │
│ male   ┆ 243   │
└────────┴───────┘

shape: (72, 2)
┌─────┬───────┐
│ age ┆ count │
│ --- ┆ ---   │
│ i64 ┆ u32   │
╞═════╪═══════╡
│ 22  ┆ 1     │
│ 31  ┆ 5     │
│ 71  ┆ 6     │
│ 45  ┆ 7     │
│ 44  ┆ 11    │
│ …   ┆ …     │
│ 55  ┆ 14    │
│ 76  ┆ 4     │
│ 86  ┆ 2     │
│ 80  ┆ 4     │
│ 85  ┆ 1     │
└─────┴───────┘

shape: (2, 2)
┌────────────┬───────┐
│ AJCC_stage ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ IIIC       ┆ 23    │
│ IV         ┆ 394   │
└────────────┴───────┘

shape: (4, 2)
┌─────────┬───────┐
│ M_stage ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ null    ┆ 137   │
│ M1A     ┆ 49    │
│ M1C     ┆ 199   │
│ M1B     ┆ 32    │
└─────────┴───────┘

shape: (3, 2)
┌──────────┬───────┐
│ LDH      ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ elevated ┆ 115   │
│ null     ┆ 143   │
│ normal   ┆ 159   │
└──────────┴───────┘

shape: (3, 2)
┌───────────┬───────┐
│ OS_status ┆ count │
│ ---       ┆ ---   │
│ f64       ┆ u32   │
╞═══════════╪═══════╡
│ 1.0       ┆ 175   │
│ null      ┆ 158   │
│ 0.0       ┆ 84    │
└───────────┴───────┘

shape: (182, 2)
┌──────────┬───────┐
│ OS_month ┆ count │
│ ---      ┆ ---   │
│ f64      ┆ u32   │
╞══════════╪═══════╡
│ 16.9     ┆ 1     │
│ 10.3     ┆ 2     │
│ 4.4      ┆ 2     │
│ 13.8     ┆ 1     │
│ 67.6     ┆ 1     │
│ …        ┆ …     │
│ 6.7      ┆ 2     │
│ 16.5     ┆ 2     │
│ 25.0     ┆ 1     │
│ 21.0     ┆ 2     │
│ 11.3     ┆ 2     │
└──────────┴───────┘

shape: (3, 2)
┌────────────┬───────┐
│ PFS_status ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ <NA>       ┆ 2     │
│ 1          ┆ 341   │
│ 0          ┆ 74    │
└────────────┴───────┘

shape: (157, 2)
┌───────────┬───────┐
│ PFS_month ┆ count │
│ ---       ┆ ---   │
│ f64       ┆ u32   │
╞═══════════╪═══════╡
│ 14.9      ┆ 2     │
│ 31.0      ┆ 1     │
│ 2.0       ┆ 3     │
│ 58.0      ┆ 1     │
│ 7.9       ┆ 4     │
│ …         ┆ …     │
│ 9.0       ┆ 3     │
│ 5.0       ┆ 1     │
│ 44.6      ┆ 1     │
│ 8.2       ┆ 2     │
│ 9.5       ┆ 1     │
└───────────┴───────┘

shape: (5, 2)
┌───────────────────────────┬───────┐
│ drug                      ┆ count │
│ ---                       ┆ ---   │
│ str                       ┆ u32   │
╞═══════════════════════════╪═══════╡
│ vemurafenib + cobimetinib ┆ 69    │
│ vemurafenib               ┆ 204   │
│ nan                       ┆ 1     │
│ dabrafenib                ┆ 48    │
│ dabrafenib + trametinib   ┆ 95    │
└───────────────────────────┴───────┘

shape: (5, 2)
┌──────┬───────┐
│ BOR  ┆ count │
│ ---  ┆ ---   │
│ str  ┆ u32   │
╞══════╪═══════╡
│ PR   ┆ 135   │
│ PD   ┆ 141   │
│ null ┆ 7     │
│ CR   ┆ 79    │
│ SD   ┆ 55    │
└──────┴───────┘

shape: (6, 2)
┌─────────────────────┬───────┐
│ BRAF_mut            ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ MND                 ┆ 19    │
│ V600R               ┆ 2     │
│ V600E; R558Q        ┆ 1     │
│ V600E; K601I; C195W ┆ 1     │
│ V600E               ┆ 340   │
│ V600K               ┆ 54    │
└─────────────────────┴───────┘

shape: (3, 2)
┌──────────────────┬───────┐
│ brain_metastasis ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│ no               ┆ 197   │
│ null             ┆ 175   │
│ yes              ┆ 45    │
└──────────────────┴───────┘

shape: (2, 2)
┌─────────────────────────┬───────┐
│ immunotherapy_treatment ┆ count │
│ ---                     ┆ ---   │
│ str                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ no                      ┆ 385   │
│ yes                     ┆ 32    │
└─────────────────────────┴───────┘

shape: (7, 2)
┌─────────────────────────────────┬───────┐
│ pre_MAPKi_treatment             ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Ipi (ipilimumab(adjuvant trial… ┆ 2     │
│ Chemotherapy                    ┆ 11    │
│ no                              ┆ 393   │
│ IFN (interferon (adjuvant sett… ┆ 1     │
│ IL-2 (High-dose IL-2)           ┆ 4     │
│ MK-3475                         ┆ 2     │
│ yes                             ┆ 4     │
└─────────────────────────────────┴───────┘

shape: (2, 2)
┌──────────┬───────┐
│ CNA_data ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ no       ┆ 351   │
│ yes      ┆ 66    │
└──────────┴───────┘

shape: (5, 2)
┌───────────────┬───────┐
│ SNV_data      ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ yes (bait_v4) ┆ 11    │
│ yes (bait_v3) ┆ 10    │
│ yes (bait_v5) ┆ 45    │
│ yes           ┆ 122   │
│ no            ┆ 229   │
└───────────────┴───────┘

shape: (2, 2)
┌──────────┬───────┐
│ GEX_data ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ yes      ┆ 253   │
│ no       ┆ 164   │
└──────────┴───────┘

shape: (9, 2)
┌─────────────────────────────────┬───────┐
│ source                          ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ doi:10.3390/cancers12082224     ┆ 53    │
│ doi:10.1172/JCI78954DS1         ┆ 22    │
│ doi:10.3390/cancers11081203     ┆ 24    │
│ doi:10.1016/j.cell.2015.07.061  ┆ 44    │
│ doi:10.1158/1078-0432.CCR-18-0… ┆ 130   │
│ doi:10.1158/1078-0432.CCR-13-3… ┆ 24    │
│ doi:10.1038/ncomms6694          ┆ 9     │
│ doi:10.1158/2159-8290.CD-13-06… ┆ 45    │
│ doi:10.1200/PO.16.00054         ┆ 66    │
└─────────────────────────────────┴───────┘

In [12]:
patient_df = patient_df.drop(pl.col(['id', 'creation_datetime', 'original_patientID', 'OS_status', 'OS_month', 'source', 'brain_metastasis', 'immunotherapy_treatment', 'M_stage', 'CNA_data', 'SNV_data', 'GEX_data']))
patient_df

shape: (417, 11)
┌───────────┬────────┬─────┬────────────┬───┬──────────────┬─────┬──────────┬──────────────────────┐
│ patientID ┆ sex    ┆ age ┆ AJCC_stage ┆ … ┆ drug         ┆ BOR ┆ BRAF_mut ┆ pre_MAPKi_treatment  │
│ ---       ┆ ---    ┆ --- ┆ ---        ┆   ┆ ---          ┆ --- ┆ ---      ┆ ---                  │
│ str       ┆ str    ┆ i64 ┆ str        ┆   ┆ str          ┆ str ┆ str      ┆ str                  │
╞═══════════╪════════╪═════╪════════════╪═══╪══════════════╪═════╪══════════╪══════════════════════╡
│ BS_000    ┆ male   ┆ 56  ┆ IV         ┆ … ┆ dabrafenib + ┆ PD  ┆ V600E    ┆ no                   │
│           ┆        ┆     ┆            ┆   ┆ trametinib   ┆     ┆          ┆                      │
│ BS_001    ┆ male   ┆ 86  ┆ IV         ┆ … ┆ dabrafenib   ┆ SD  ┆ V600E    ┆ no                   │
│ BS_002    ┆ female ┆ 47  ┆ IV         ┆ … ┆ dabrafenib + ┆ CR  ┆ V600E    ┆ no                   │
│           ┆        ┆     ┆            ┆   ┆ trametinib   ┆     ┆          ┆                      │
│ BS_003    ┆ female ┆ 50  ┆ IV         ┆ … ┆ vemurafenib  ┆ PD  ┆ V600E    ┆ no                   │
│ BS_004    ┆ female ┆ 47  ┆ IV         ┆ … ┆ dabrafenib + ┆ PD  ┆ V600K    ┆ no                   │
│           ┆        ┆     ┆            ┆   ┆ trametinib   ┆     ┆          ┆                      │
│ …         ┆ …      ┆ …   ┆ …          ┆ … ┆ …            ┆ …   ┆ …        ┆ …                    │
│ HL_40     ┆ male   ┆ 47  ┆ IV         ┆ … ┆ vemurafenib  ┆ PR  ┆ V600E    ┆ no                   │
│ HL_41     ┆ male   ┆ 39  ┆ IV         ┆ … ┆ vemurafenib  ┆ PR  ┆ V600E    ┆ no                   │
│ HL_42     ┆ male   ┆ 84  ┆ IV         ┆ … ┆ dabrafenib   ┆ PR  ┆ V600E    ┆ no                   │
│ HL_43     ┆ female ┆ 41  ┆ IV         ┆ … ┆ vemurafenib  ┆ PR  ┆ V600E    ┆ no                   │
│ HL_44     ┆ male   ┆ 83  ┆ IV         ┆ … ┆ vemurafenib  ┆ SD  ┆ V600K    ┆ no                   │
└───────────┴────────┴─────┴────────────┴───┴──────────────┴─────┴──────────┴──────────────────────┘

In [13]:
gex_df = pl.read_csv("gex_data/gex.csv")
merge_df = gex_df.join(patient_df, on='patientID', how='inner')
merge_df

shape: (132, 51_477)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────────┬─────┬──────────┬──────────────┐
│ patientID ┆ LOC341056 ┆ CERS3-AS1 ┆ DPP10    ┆ … ┆ drug          ┆ BOR ┆ BRAF_mut ┆ pre_MAPKi_tr │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---           ┆ --- ┆ ---      ┆ eatment      │
│ str       ┆ f64       ┆ f64       ┆ f64      ┆   ┆ str           ┆ str ┆ str      ┆ ---          │
│           ┆           ┆           ┆          ┆   ┆               ┆     ┆          ┆ str          │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════════╪═════╪══════════╪══════════════╡
│ YR_3053   ┆ null      ┆ 0.0       ┆ 0.008695 ┆ … ┆ vemurafenib   ┆ PD  ┆ V600E    ┆ no           │
│ YR_3708   ┆ null      ┆ 0.0       ┆ 0.001527 ┆ … ┆ vemurafenib   ┆ CR  ┆ V600E    ┆ no           │
│ YR_3705   ┆ null      ┆ 0.0       ┆ 0.002444 ┆ … ┆ vemurafenib   ┆ CR  ┆ V600E    ┆ no           │
│ YR_1106   ┆ null      ┆ 0.0       ┆ 0.007547 ┆ … ┆ vemurafenib + ┆ PD  ┆ V600E    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ cobimetinib   ┆     ┆          ┆              │
│ YR_1110   ┆ null      ┆ 0.0       ┆ 0.371447 ┆ … ┆ vemurafenib + ┆ PD  ┆ V600E    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ cobimetinib   ┆     ┆          ┆              │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …             ┆ …   ┆ …        ┆ …            │
│ KC_19     ┆ 0.0       ┆ null      ┆ 0.0      ┆ … ┆ dabrafenib +  ┆ PR  ┆ V600E    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ trametinib    ┆     ┆          ┆              │
│ KC_22     ┆ 0.04      ┆ null      ┆ 0.24     ┆ … ┆ dabrafenib +  ┆ PR  ┆ V600K    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ trametinib    ┆     ┆          ┆              │
│ KC_24     ┆ 0.0       ┆ null      ┆ 0.03     ┆ … ┆ vemurafenib   ┆ PR  ┆ V600K    ┆ no           │
│ KC_25     ┆ 0.0       ┆ null      ┆ 0.0      ┆ … ┆ dabrafenib +  ┆ PR  ┆ V600K    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ trametinib    ┆     ┆          ┆              │
│ KC_34     ┆ 0.0       ┆ null      ┆ 0.0      ┆ … ┆ dabrafenib +  ┆ PR  ┆ V600E    ┆ no           │
│           ┆           ┆           ┆          ┆   ┆ trametinib    ┆     ┆          ┆              │
└───────────┴───────────┴───────────┴──────────┴───┴───────────────┴─────┴──────────┴──────────────┘

In [14]:
merge_df.select(pl.all().null_count())

shape: (1, 51_477)
┌───────────┬───────────┬───────────┬───────┬───┬──────┬─────┬──────────┬─────────────────────┐
│ patientID ┆ LOC341056 ┆ CERS3-AS1 ┆ DPP10 ┆ … ┆ drug ┆ BOR ┆ BRAF_mut ┆ pre_MAPKi_treatment │
│ ---       ┆ ---       ┆ ---       ┆ ---   ┆   ┆ ---  ┆ --- ┆ ---      ┆ ---                 │
│ u32       ┆ u32       ┆ u32       ┆ u32   ┆   ┆ u32  ┆ u32 ┆ u32      ┆ u32                 │
╞═══════════╪═══════════╪═══════════╪═══════╪═══╪══════╪═════╪══════════╪═════════════════════╡
│ 0         ┆ 118       ┆ 64        ┆ 20    ┆ … ┆ 0    ┆ 0   ┆ 0        ┆ 0                   │
└───────────┴───────────┴───────────┴───────┴───┴──────┴─────┴──────────┴─────────────────────┘

In [15]:
threshold = merge_df.height * 0.5
cols_to_keep = [col.name for col in merge_df.iter_columns() if col.null_count() <= threshold]
merge_df = merge_df.select(cols_to_keep)

In [16]:
merge_df

shape: (132, 27_863)
┌───────────┬───────────┬──────────┬─────────────┬───┬──────────────┬─────┬──────────┬─────────────┐
│ patientID ┆ CERS3-AS1 ┆ DPP10    ┆ SNORD115-39 ┆ … ┆ drug         ┆ BOR ┆ BRAF_mut ┆ pre_MAPKi_t │
│ ---       ┆ ---       ┆ ---      ┆ ---         ┆   ┆ ---          ┆ --- ┆ ---      ┆ reatment    │
│ str       ┆ f64       ┆ f64      ┆ f64         ┆   ┆ str          ┆ str ┆ str      ┆ ---         │
│           ┆           ┆          ┆             ┆   ┆              ┆     ┆          ┆ str         │
╞═══════════╪═══════════╪══════════╪═════════════╪═══╪══════════════╪═════╪══════════╪═════════════╡
│ YR_3053   ┆ 0.0       ┆ 0.008695 ┆ 0.0         ┆ … ┆ vemurafenib  ┆ PD  ┆ V600E    ┆ no          │
│ YR_3708   ┆ 0.0       ┆ 0.001527 ┆ 1.519615    ┆ … ┆ vemurafenib  ┆ CR  ┆ V600E    ┆ no          │
│ YR_3705   ┆ 0.0       ┆ 0.002444 ┆ 62.123667   ┆ … ┆ vemurafenib  ┆ CR  ┆ V600E    ┆ no          │
│ YR_1106   ┆ 0.0       ┆ 0.007547 ┆ 0.2276      ┆ … ┆ vemurafenib  ┆ PD  ┆ V600E    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ +            ┆     ┆          ┆             │
│           ┆           ┆          ┆             ┆   ┆ cobimetinib  ┆     ┆          ┆             │
│ YR_1110   ┆ 0.0       ┆ 0.371447 ┆ 1.557936    ┆ … ┆ vemurafenib  ┆ PD  ┆ V600E    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ +            ┆     ┆          ┆             │
│           ┆           ┆          ┆             ┆   ┆ cobimetinib  ┆     ┆          ┆             │
│ …         ┆ …         ┆ …        ┆ …           ┆ … ┆ …            ┆ …   ┆ …        ┆ …           │
│ KC_19     ┆ null      ┆ 0.0      ┆ 0.0         ┆ … ┆ dabrafenib + ┆ PR  ┆ V600E    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ trametinib   ┆     ┆          ┆             │
│ KC_22     ┆ null      ┆ 0.24     ┆ 0.0         ┆ … ┆ dabrafenib + ┆ PR  ┆ V600K    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ trametinib   ┆     ┆          ┆             │
│ KC_24     ┆ null      ┆ 0.03     ┆ 0.0         ┆ … ┆ vemurafenib  ┆ PR  ┆ V600K    ┆ no          │
│ KC_25     ┆ null      ┆ 0.0      ┆ 0.0         ┆ … ┆ dabrafenib + ┆ PR  ┆ V600K    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ trametinib   ┆     ┆          ┆             │
│ KC_34     ┆ null      ┆ 0.0      ┆ 0.0         ┆ … ┆ dabrafenib + ┆ PR  ┆ V600E    ┆ no          │
│           ┆           ┆          ┆             ┆   ┆ trametinib   ┆     ┆          ┆             │
└───────────┴───────────┴──────────┴─────────────┴───┴──────────────┴─────┴──────────┴─────────────┘

In [17]:
pl.Config.set_tbl_rows(-1)   # show all rows

merge_df.select([
    pl.col("patientID"),
    pl.sum_horizontal(pl.all().is_null()).alias("null_count")
])

shape: (132, 2)
┌────────────┬────────────┐
│ patientID  ┆ null_count │
│ ---        ┆ ---        │
│ str        ┆ u32        │
╞════════════╪════════════╡
│ YR_3053    ┆ 0          │
│ YR_3708    ┆ 0          │
│ YR_3705    ┆ 0          │
│ YR_1106    ┆ 0          │
│ YR_1110    ┆ 0          │
│ YR_1402    ┆ 0          │
│ YR_1154    ┆ 0          │
│ YR_2097    ┆ 0          │
│ YR_2078    ┆ 0          │
│ YR_2203    ┆ 0          │
│ YR_2096    ┆ 0          │
│ YR_2208    ┆ 0          │
│ YR_2362    ┆ 0          │
│ YR_2066    ┆ 0          │
│ YR_2083    ┆ 0          │
│ YR_2347    ┆ 0          │
│ YR_2420    ┆ 0          │
│ YR_2094    ┆ 0          │
│ YR_2346    ┆ 0          │
│ YR_2210    ┆ 0          │
│ YR_2281    ┆ 0          │
│ YR_2319    ┆ 0          │
│ YR_2296    ┆ 0          │
│ YR_2261    ┆ 0          │
│ YR_2035    ┆ 0          │
│ YR_2214    ┆ 0          │
│ YR_2220    ┆ 0          │
│ YR_2382    ┆ 0          │
│ YR_2148    ┆ 0          │
│ YR_2191    ┆ 0          │
│ YR_2207    ┆ 0          │
│ YR_2174    ┆ 0          │
│ YR_2378    ┆ 0          │
│ YR_2136    ┆ 0          │
│ YR_2484    ┆ 0          │
│ YR_2048    ┆ 0          │
│ YR_2405    ┆ 0          │
│ YR_2466    ┆ 0          │
│ YR_2472    ┆ 0          │
│ YR_2459    ┆ 0          │
│ YR_2337    ┆ 0          │
│ YR_2434    ┆ 0          │
│ YR_2063    ┆ 1          │
│ YR_2131    ┆ 0          │
│ YR_2211    ┆ 0          │
│ YR_2300    ┆ 0          │
│ YR_2443    ┆ 0          │
│ YR_2390    ┆ 0          │
│ YR_2036    ┆ 1          │
│ YR_2363    ┆ 0          │
│ YR_2425    ┆ 0          │
│ YR_2380    ┆ 0          │
│ YR_2409    ┆ 0          │
│ YR_2496    ┆ 0          │
│ YR_2494    ┆ 0          │
│ YR_2417    ┆ 0          │
│ YR_102011  ┆ 0          │
│ YR_106006  ┆ 0          │
│ YR_103001  ┆ 0          │
│ YR_5306    ┆ 0          │
│ YR_5311    ┆ 0          │
│ YR_8902    ┆ 0          │
│ YR_112016  ┆ 0          │
│ YR_113005  ┆ 0          │
│ YR_106008  ┆ 0          │
│ YR_102005  ┆ 0          │
│ YR_112008  ┆ 0          │
│ YR_104002  ┆ 0          │
│ LM_1       ┆ 27825      │
│ LM_2       ┆ 27825      │
│ LM_4       ┆ 27825      │
│ LM_6       ┆ 27825      │
│ LM_7       ┆ 27824      │
│ LM_8       ┆ 27825      │
│ LM_9       ┆ 27824      │
│ LM_10      ┆ 27825      │
│ LM_11      ┆ 27825      │
│ LM_14      ┆ 27824      │
│ LM_15      ┆ 27825      │
│ LM_16      ┆ 27825      │
│ LM_18      ┆ 27825      │
│ LM_19      ┆ 27824      │
│ LM_20      ┆ 27824      │
│ LM_21      ┆ 27825      │
│ LM_23      ┆ 27825      │
│ LM_25      ┆ 27825      │
│ LM_26      ┆ 27825      │
│ LM_27      ┆ 27824      │
│ RL_WMD-039 ┆ 10474      │
│ RL_WMD-029 ┆ 10474      │
│ RL_MTP-020 ┆ 10474      │
│ RL_MTP-064 ┆ 10474      │
│ RL_WMD-012 ┆ 10474      │
│ RL_WMD-025 ┆ 10474      │
│ RL_MTP-063 ┆ 10474      │
│ RL_WMD-009 ┆ 10474      │
│ RL_WMD-021 ┆ 10474      │
│ RL_WMD-006 ┆ 10474      │
│ RL_MTP-014 ┆ 10474      │
│ RL_WMD-007 ┆ 10474      │
│ RL_WMD-027 ┆ 10474      │
│ RL_MTP-080 ┆ 10474      │
│ RL_MTP-066 ┆ 10474      │
│ RL_MTP-095 ┆ 10474      │
│ RL_SMU-017 ┆ 10474      │
│ RL_WMD-013 ┆ 10474      │
│ RL_MTP-093 ┆ 10474      │
│ RL_MTP-099 ┆ 10475      │
│ RL_WMD-035 ┆ 10474      │
│ LR_WMD-022 ┆ 10474      │
│ LR_SMU-030 ┆ 10474      │
│ LR_MTP-034 ┆ 10474      │
│ LR_WMD-033 ┆ 10474      │
│ LR_SMU-020 ┆ 10474      │
│ LR_SMU-034 ┆ 10474      │
│ LR_MTP-073 ┆ 10474      │
│ LR_SMU-028 ┆ 10474      │
│ LR_WMD-017 ┆ 10474      │
│ KC_2       ┆ 7082       │
│ KC_6       ┆ 7082       │
│ KC_7       ┆ 7082       │
│ KC_9       ┆ 7082       │
│ KC_10      ┆ 7082       │
│ KC_12      ┆ 7082       │
│ KC_13      ┆ 7082       │
│ KC_15      ┆ 7082       │
│ KC_16      ┆ 7082       │
│ KC_19      ┆ 7082       │
│ KC_22      ┆ 7082       │
│ KC_24      ┆ 7082       │
│ KC_25      ┆ 7082       │
│ KC_34      ┆ 7082       │
└────────────┴────────────┘

In [18]:
merge_df = merge_df.filter(
    pl.sum_horizontal(pl.all().is_null()) <= merge_df.width * 0.5
)
merge_df

shape: (112, 27_863)
┌────────────┬───────────┬───────────┬─────────────┬───┬─────────────┬─────┬──────────┬────────────┐
│ patientID  ┆ CERS3-AS1 ┆ DPP10     ┆ SNORD115-39 ┆ … ┆ drug        ┆ BOR ┆ BRAF_mut ┆ pre_MAPKi_ │
│ ---        ┆ ---       ┆ ---       ┆ ---         ┆   ┆ ---         ┆ --- ┆ ---      ┆ treatment  │
│ str        ┆ f64       ┆ f64       ┆ f64         ┆   ┆ str         ┆ str ┆ str      ┆ ---        │
│            ┆           ┆           ┆             ┆   ┆             ┆     ┆          ┆ str        │
╞════════════╪═══════════╪═══════════╪═════════════╪═══╪═════════════╪═════╪══════════╪════════════╡
│ YR_3053    ┆ 0.0       ┆ 0.008695  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_3708    ┆ 0.0       ┆ 0.001527  ┆ 1.519615    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_3705    ┆ 0.0       ┆ 0.002444  ┆ 62.123667   ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_1106    ┆ 0.0       ┆ 0.007547  ┆ 0.2276      ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_1110    ┆ 0.0       ┆ 0.371447  ┆ 1.557936    ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_1402    ┆ 0.0       ┆ 2.260809  ┆ 2.56326     ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_1154    ┆ 0.0       ┆ 0.002698  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2097    ┆ 0.0       ┆ 0.113995  ┆ 2.724395    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2078    ┆ 0.0       ┆ 0.062154  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│ YR_2203    ┆ 0.0       ┆ 0.0       ┆ 0.903613    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2096    ┆ 0.0       ┆ 0.0       ┆ 0.508823    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2208    ┆ 0.0       ┆ 0.0       ┆ 0.246508    ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2362    ┆ 0.0       ┆ 0.002672  ┆ 0.483482    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2066    ┆ 0.0       ┆ 0.004917  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ MND      ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2083    ┆ 0.0       ┆ 0.002675  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2347    ┆ 0.03851   ┆ 0.03917   ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600K    ┆ no         │
│ YR_2420    ┆ 0.041805  ┆ 0.040588  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2094    ┆ 0.0       ┆ 0.0       ┆ 1.180654    ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2346    ┆ 0.0       ┆ 0.00846   ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600K    ┆ no         │
│ YR_2210    ┆ 0.0       ┆ 4.527339  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2281    ┆ 0.034616  ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2319    ┆ 0.0       ┆ 0.005618  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2296    ┆ 0.0       ┆ 0.0023    ┆ 0.208073    ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2261    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2035    ┆ 0.0       ┆ 0.001543  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2214    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2220    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2382    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2148    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2191    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2207    ┆ 0.0       ┆ 0.010424  ┆ 2.514913    ┆ … ┆ vemurafenib ┆ CR  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2174    ┆ 0.0       ┆ 0.00246   ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2378    ┆ 0.02648   ┆ 0.014691  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2136    ┆ 0.0       ┆ 0.0       ┆ 11.807294   ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2484    ┆ 0.0       ┆ 0.789349  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2048    ┆ 0.0       ┆ 0.0       ┆ 0.328641    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2405    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2466    ┆ 0.0       ┆ 0.714037  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ MND      ┆ no         │
│ YR_2472    ┆ 0.0       ┆ 0.0       ┆ 1.677648    ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│ YR_2459    ┆ 0.0       ┆ 0.396813  ┆ 0.222993    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2337    ┆ 0.0       ┆ 0.002882  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2434    ┆ 0.0       ┆ 0.006587  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2063    ┆ 0.0       ┆ 0.099745  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2131    ┆ 0.0       ┆ 0.005152  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2211    ┆ 0.0       ┆ 0.004005  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2300    ┆ 0.0       ┆ 0.321271  ┆ 2.603031    ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2443    ┆ 0.0       ┆ 0.026856  ┆ 4.252185    ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2390    ┆ 0.0       ┆ 0.006351  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2036    ┆ 0.0       ┆ 0.053905  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_2363    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ cobimetinib ┆     ┆          ┆            │
│ YR_2425    ┆ 0.061601  ┆ 0.049365  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2380    ┆ 0.0       ┆ 1.672856  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2409    ┆ 0.0       ┆ 0.20775   ┆ 16.19843    ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2496    ┆ 0.054186  ┆ 1.230041  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_2494    ┆ 0.0       ┆ 0.016185  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ MND      ┆ no         │
│ YR_2417    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_102011  ┆ 0.0       ┆ 0.018071  ┆ 0.545       ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_106006  ┆ 0.0       ┆ 4.650245  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_103001  ┆ 0.0       ┆ 0.089982  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_5306    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ MND      ┆ no         │
│ YR_5311    ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│ YR_8902    ┆ 0.0       ┆ 0.080671  ┆ 5.581424    ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_112016  ┆ 0.0       ┆ 0.013863  ┆ 0.0         ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_113005  ┆ 0.0       ┆ 1.211781  ┆ 2.621409    ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_106008  ┆ 0.0       ┆ 0.007445  ┆ 3.70452     ┆ … ┆ vemurafenib ┆ PD  ┆ V600E    ┆ no         │
│ YR_102005  ┆ 0.100136  ┆ 0.003086  ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ V600K    ┆ no         │
│ YR_112008  ┆ 0.0       ┆ 1.550583  ┆ 180.372751  ┆ … ┆ vemurafenib ┆ CR  ┆ V600E    ┆ no         │
│ YR_104002  ┆ 0.0       ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ PD  ┆ MND      ┆ no         │
│ RL_WMD-039 ┆ null      ┆ 2.138987  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_WMD-029 ┆ null      ┆ -0.079975 ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_MTP-020 ┆ null      ┆ 28.39646  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600K    ┆ no         │
│ RL_MTP-064 ┆ null      ┆ 0.2584395 ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600K    ┆ no         │
│ RL_WMD-012 ┆ null      ┆ -1.844651 ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600K    ┆ no         │
│ RL_WMD-025 ┆ null      ┆ 4.7743715 ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_MTP-063 ┆ null      ┆ 1.9192915 ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_WMD-009 ┆ null      ┆ -1.615468 ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_WMD-021 ┆ null      ┆ 7.507644  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│ RL_WMD-006 ┆ null      ┆ 2.0216487 ┆ null        ┆ … ┆ dabrafenib  ┆ PD  ┆ V600K    ┆ no         │
│ RL_MTP-014 ┆ null      ┆ 44.13052  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600K    ┆ no         │
│ RL_WMD-007 ┆ null      ┆ 7.7022075 ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│ RL_WMD-027 ┆ null      ┆ 5.377746  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│ RL_MTP-080 ┆ null      ┆ -5.26254  ┆ null        ┆ … ┆ dabrafenib  ┆ PD  ┆ V600E    ┆ no         │
│ RL_MTP-066 ┆ null      ┆ 1.494313  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│ RL_MTP-095 ┆ null      ┆ 6.575225  ┆ null        ┆ … ┆ dabrafenib  ┆ CR  ┆ V600E    ┆ no         │
│ RL_SMU-017 ┆ null      ┆ 8.841221  ┆ null        ┆ … ┆ vemurafenib ┆ PR  ┆ V600E    ┆ no         │
│ RL_WMD-013 ┆ null      ┆ 6.402246  ┆ null        ┆ … ┆ vemurafenib ┆ PR  ┆ V600E    ┆ no         │
│ RL_MTP-093 ┆ null      ┆ 2.632378  ┆ null        ┆ … ┆ vemurafenib ┆ PR  ┆ V600K    ┆ no         │
│ RL_MTP-099 ┆ null      ┆ -1.648716 ┆ null        ┆ … ┆ vemurafenib ┆ PD  ┆ V600R    ┆ no         │
│ RL_WMD-035 ┆ null      ┆ 3.078466  ┆ null        ┆ … ┆ vemurafenib ┆ SD  ┆ V600E    ┆ no         │
│ LR_WMD-022 ┆ null      ┆ 63.12509  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_SMU-030 ┆ null      ┆ 1.987516  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_MTP-034 ┆ null      ┆ 9.6874465 ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_WMD-033 ┆ null      ┆ 3.610836  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_SMU-020 ┆ null      ┆ 1.12659   ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_SMU-034 ┆ null      ┆ 7.420394  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_MTP-073 ┆ null      ┆ 7.780053  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_SMU-028 ┆ null      ┆ 3.570803  ┆ null        ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ LR_WMD-017 ┆ null      ┆ 5.877273  ┆ null        ┆ … ┆ dabrafenib  ┆ SD  ┆ V600K    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_2       ┆ null      ┆ 0.01      ┆ 0.0         ┆ … ┆ vemurafenib ┆ PR  ┆ V600E    ┆ no         │
│ KC_6       ┆ null      ┆ 0.03      ┆ 0.0         ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_7       ┆ null      ┆ 0.0       ┆ 0.0         ┆ … ┆ dabrafenib  ┆ CR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_9       ┆ null      ┆ 0.0       ┆ 0.0         ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_10      ┆ null      ┆ 0.07      ┆ 0.0         ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_12      ┆ null      ┆ 0.01      ┆ 0.0         ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_13      ┆ null      ┆ 0.0       ┆ 0.0         ┆ … ┆ dabrafenib  ┆ PR  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │
│ KC_15      ┆ null      ┆ 0.0       ┆ 0.0         ┆ … ┆ vemurafenib ┆ SD  ┆ V600E    ┆ no         │
│ KC_16      ┆ null      ┆ 0.07      ┆ 0.0         ┆ … ┆ dabrafenib  ┆ SD  ┆ V600E    ┆ no         │
│            ┆           ┆           ┆             ┆   ┆ +           ┆     ┆          ┆            │
│            ┆           ┆           ┆             ┆   ┆ trametinib  ┆     ┆          ┆            │

In [19]:
merge_df.write_csv('gex_data/gex_patient.csv')