## Helper functions

In [132]:
import pandas as pd
import numpy as np

In [133]:
def count_unique_value_per_class(df):
    for feat in df.columns.tolist():
        print(f'{df[feat].value_counts()}\n')
        
def count_null_per_class(df):
    print(f'{df.isnull().sum()}')

## Clinical dataset

In [134]:
clinical_df = pd.read_csv("dataset/clinical.csv")
display(clinical_df)

,id,creation_datetime,patientID,original_patientID,sex,age,AJCC_stage,M_stage,LDH,OS_status,...,drug,BOR,BRAF_mut,brain_metastasis,immunotherapy_treatment,pre_MAPKi_treatment,CNA_data,SNV_data,GEX_data,source
0,1,2025-04-23 22:54:49.773923,BS_000,0,male,56,IV,NaN,normal,0.0,...,dabrafenib + trametinib,PD,V600E,no,no,no,no,yes,no,doi:10.3390/cancers12082224
1,2,2025-04-23 22:54:49.802003,BS_001,1,male,86,IV,NaN,normal,1.0,...,dabrafenib,SD,V600E,no,no,no,no,yes,no,doi:10.3390/cancers12082224
2,3,2025-04-23 22:54:49.807526,BS_002,2,female,47,IV,NaN,normal,0.0,...,dabrafenib + trametinib,CR,V600E,no,no,no,no,yes,no,doi:10.3390/cancers12082224
3,4,2025-04-23 22:54:49.813005,BS_003,3,female,50,IV,NaN,NaN,1.0,...,vemurafenib,PD,V600E,no,no,no,no,yes,no,doi:10.3390/cancers12082224
4,5,2025-04-23 22:54:49.818403,BS_004,4,female,47,IV,NaN,elevated,1.0,...,dabrafenib + trametinib,PD,V600K,no,no,no,no,yes,no,doi:10.3390/cancers12082224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,413,2025-04-23 22:54:53.873737,HL_40,Shi-40,male,47,IV,M1C,NaN,NaN,...,vemurafenib,PR,V600E,no,no,no,no,no,yes,doi:10.1016/j.cell.2015.07.061
413,414,2025-04-23 22:54:53.880906,HL_41,Shi-41,male,39,IV,M1A,NaN,NaN,...,vemurafenib,PR,V600E,no,no,no,no,no,yes,doi:10.1016/j.cell.2015.07.061
414,415,2025-04-23 22:54:53.887897,HL_42,Shi-42,male,84,IV,M1C,NaN,NaN,...,dabrafenib,PR,V600E,no,no,no,no,no,yes,doi:10.1016/j.cell.2015.07.061
415,416,2025-04-23 22:54:53.895830,HL_43,Shi-43,female,41,IV,M1C,NaN,NaN,...,vemurafenib,PR,V600E,no,no,no,no,no,yes,doi:10.1016/j.cell.2015.07.061
416,417,2025-04-23 22:54:53.912355,HL_44,Shi-44,male,83,IV,M1C,NaN,NaN,...,vemurafenib,SD,V600K,no,no,no,no,no,yes,doi:10.1016/j.cell.2015.07.061

In [135]:
clinical_df.isnull().sum()

id                           0
creation_datetime            0
patientID                    0
original_patientID           0
sex                          0
age                          0
AJCC_stage                   0
M_stage                    137
LDH                        143
OS_status                  158
OS_month                   160
PFS_status                   2
PFS_month                    0
drug                         1
BOR                          7
BRAF_mut                     0
brain_metastasis           175
immunotherapy_treatment      0
pre_MAPKi_treatment          0
CNA_data                     0
SNV_data                     0
GEX_data                     0
source                       0
dtype: int64

In [136]:
count_unique_value_per_class(clinical_df)

id
1      1
2      1
3      1
4      1
5      1
      ..
413    1
414    1
415    1
416    1
417    1
Name: count, Length: 417, dtype: int64

creation_datetime
2025-04-23 22:54:49.773923    1
2025-04-23 22:54:49.802003    1
2025-04-23 22:54:49.807526    1
2025-04-23 22:54:49.813005    1
2025-04-23 22:54:49.818403    1
                             ..
2025-04-23 22:54:53.873737    1
2025-04-23 22:54:53.880906    1
2025-04-23 22:54:53.887897    1
2025-04-23 22:54:53.895830    1
2025-04-23 22:54:53.912355    1
Name: count, Length: 417, dtype: int64

patientID
BS_000    1
BS_001    1
BS_002    1
BS_003    1
BS_004    1
         ..
HL_40     1
HL_41     1
HL_42     1
HL_43     1
HL_44     1
Name: count, Length: 417, dtype: int64

original_patientID
2         3
4         3
6         3
7         3
9         3
         ..
Shi-40    1
Shi-41    1
Shi-42    1
Shi-43    1
Shi-44    1
Name: count, Length: 371, dtype: int64

sex
male      243
female    174
Name: count, dtype: int64

age
51    15
62    15
55    14
47    13
43    12
      ..
91     1
18     1
94     1
27     1
37     1
Name: count, Length: 72, dtype: int64

AJCC_stage
IV      394
IIIC     23
Name: count, dtype: int64

M_stage
M1C    199
M1A     49
M1B     32
Name: count, dtype: int64

LDH
normal      159
elevated    115
Name: count, dtype: int64

OS_status
1.0    175
0.0     84
Name: count, dtype: int64

OS_month
8.4     5
7.5     5
2.6     4
6.9     4
15.0    4
       ..
12.5    1
73.0    1
33.5    1
26.2    1
24.5    1
Name: count, Length: 181, dtype: int64

PFS_status
1.0    341
0.0     74
Name: count, dtype: int64

PFS_month
1.9     16
1.4     13
2.8      9
1.8      9
3.7      9
        ..
5.0      1
10.8     1
12.4     1
9.7      1
5.3      1
Name: count, Length: 157, dtype: int64

drug
vemurafenib                  204
dabrafenib + trametinib       95
vemurafenib + cobimetinib     69
dabrafenib                    48
Name: count, dtype: int64

BOR
PD    141
PR    135
CR     79
SD     55
Name: count, dtype: int64

BRAF_mut
V600E                  340
V600K                   54
MND                     19
V600R                    2
V600E; R558Q             1
V600E; K601I; C195W      1
Name: count, dtype: int64

brain_metastasis
no     197
yes     45
Name: count, dtype: int64

immunotherapy_treatment
no     385
yes     32
Name: count, dtype: int64

pre_MAPKi_treatment
no                                     393
Chemotherapy                            11
IL-2 (High-dose IL-2)                    4
yes                                      4
MK-3475                                  2
Ipi (ipilimumab(adjuvant trial))         2
IFN (interferon (adjuvant setting))      1
Name: count, dtype: int64

CNA_data
no     351
yes     66
Name: count, dtype: int64

SNV_data
no               229
yes              122
yes (bait_v5)     45
yes (bait_v4)     11
yes (bait_v3)     10
Name: count, dtype: int64

GEX_data
yes    253
no     164
Name: count, dtype: int64

source
doi:10.1158/1078-0432.CCR-18-0720    130
doi:10.1200/PO.16.00054               66
doi:10.3390/cancers12082224           53
doi:10.1158/2159-8290.CD-13-0617      45
doi:10.1016/j.cell.2015.07.061        44
doi:10.3390/cancers11081203           24
doi:10.1158/1078-0432.CCR-13-3122     24
doi:10.1172/JCI78954DS1               22
doi:10.1038/ncomms6694                 9
Name: count, dtype: int64

In [137]:
# brain_metastasis, M_stage - many missing values
# AJCC_stage, immunotherapy_treatment - highly imbalance class
# OS_status, OS_month - not required
# CNA_data, SNV_data, GEX_data - redundant
clinical_df.drop(columns=['id', 'creation_datetime', 'original_patientID', 'OS_status', 'OS_month', 'source', 'brain_metastasis', 'immunotherapy_treatment', 'M_stage', 'AJCC_stage', 'CNA_data', 'SNV_data', 'GEX_data'], inplace=True)
clinical_df.isnull().sum()

patientID                0
sex                      0
age                      0
LDH                    143
PFS_status               2
PFS_month                0
drug                     1
BOR                      7
BRAF_mut                 0
pre_MAPKi_treatment      0
dtype: int64

In [138]:
clinical_df

,patientID,sex,age,LDH,PFS_status,PFS_month,drug,BOR,BRAF_mut,pre_MAPKi_treatment
0,BS_000,male,56,normal,1.0,30.5,dabrafenib + trametinib,PD,V600E,no
1,BS_001,male,86,normal,0.0,24.1,dabrafenib,SD,V600E,no
2,BS_002,female,47,normal,0.0,14.1,dabrafenib + trametinib,CR,V600E,no
3,BS_003,female,50,NaN,1.0,1.6,vemurafenib,PD,V600E,no
4,BS_004,female,47,elevated,1.0,11.9,dabrafenib + trametinib,PD,V600K,no
...,...,...,...,...,...,...,...,...,...,...
412,HL_40,male,47,NaN,1.0,3.0,vemurafenib,PR,V600E,no
413,HL_41,male,39,NaN,1.0,4.0,vemurafenib,PR,V600E,no
414,HL_42,male,84,NaN,1.0,8.0,dabrafenib,PR,V600E,no
415,HL_43,female,41,NaN,1.0,10.9,vemurafenib,PR,V600E,no
416,HL_44,male,83,NaN,1.0,4.4,vemurafenib,SD,V600K,no

In [139]:
count_unique_value_per_class(clinical_df)

patientID
BS_000    1
BS_001    1
BS_002    1
BS_003    1
BS_004    1
         ..
HL_40     1
HL_41     1
HL_42     1
HL_43     1
HL_44     1
Name: count, Length: 417, dtype: int64

sex
male      243
female    174
Name: count, dtype: int64

age
51    15
62    15
55    14
47    13
43    12
      ..
91     1
18     1
94     1
27     1
37     1
Name: count, Length: 72, dtype: int64

LDH
normal      159
elevated    115
Name: count, dtype: int64

PFS_status
1.0    341
0.0     74
Name: count, dtype: int64

PFS_month
1.9     16
1.4     13
2.8      9
1.8      9
3.7      9
        ..
5.0      1
10.8     1
12.4     1
9.7      1
5.3      1
Name: count, Length: 157, dtype: int64

drug
vemurafenib                  204
dabrafenib + trametinib       95
vemurafenib + cobimetinib     69
dabrafenib                    48
Name: count, dtype: int64

BOR
PD    141
PR    135
CR     79
SD     55
Name: count, dtype: int64

BRAF_mut
V600E                  340
V600K                   54
MND                     19
V600R                    2
V600E; R558Q             1
V600E; K601I; C195W      1
Name: count, dtype: int64

pre_MAPKi_treatment
no                                     393
Chemotherapy                            11
IL-2 (High-dose IL-2)                    4
yes                                      4
MK-3475                                  2
Ipi (ipilimumab(adjuvant trial))         2
IFN (interferon (adjuvant setting))      1
Name: count, dtype: int64

## SNV dataset

In [140]:
snvs_df = pd.read_csv("dataset/snvs.csv")
snvs_df

,id,creation_datetime,patientID,sample_id,HGNC,HGVSp,HGVSp_short,uniprot_id,consequence,variant_classification,...,chromosome,start_position,end_position,strand,ref_allele,tumor_allele_1,tumor_allele_2,temporality,other_prelevements,source
0,7,2025-04-23 22:54:57.359695,BS_000,BSAM000,TERT_promoter,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers12082224
1,35,2025-04-23 22:54:57.359972,BS_000,BSAM000,BRAF,NaN,V600E,P15056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers12082224
2,42,2025-04-23 22:54:57.360086,BS_001,BSAM001,TERT_promoter,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers12082224
3,70,2025-04-23 22:54:57.360353,BS_001,BSAM001,BRAF,NaN,V600E,P15056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers12082224
4,77,2025-04-23 22:54:57.360441,BS_002,BSAM002,TERT_promoter,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers12082224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48604,50338,2025-04-23 22:55:03.205535,LM_27,LMSAM_27,DDR2,NaN,M441I,Q16832,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers11081203
48605,50339,2025-04-23 22:55:03.205546,LM_27,LMSAM_27,RAC1,NaN,P29S,P63000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers11081203
48606,50340,2025-04-23 22:55:03.205556,LM_27,LMSAM_27,MET,NaN,N375S,P08581,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers11081203
48607,50341,2025-04-23 22:55:03.205566,LM_27,LMSAM_27,BRAF,NaN,V600E,P15056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers11081203
48608,50342,2025-04-23 22:55:03.205577,LM_27,LMSAM_27,AKT1,NaN,E17K,P31749,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment,NaN,doi:10.3390/cancers11081203

In [141]:
count_unique_value_per_class(snvs_df)

id
7        1
35       1
42       1
70       1
77       1
        ..
50338    1
50339    1
50340    1
50341    1
50342    1
Name: count, Length: 48609, dtype: int64

creation_datetime
2025-04-23 22:54:57.359695    1
2025-04-23 22:54:57.359972    1
2025-04-23 22:54:57.360086    1
2025-04-23 22:54:57.360353    1
2025-04-23 22:54:57.360441    1
                             ..
2025-04-23 22:55:03.205535    1
2025-04-23 22:55:03.205546    1
2025-04-23 22:55:03.205556    1
2025-04-23 22:55:03.205566    1
2025-04-23 22:55:03.205577    1
Name: count, Length: 48609, dtype: int64

patientID
VS_Pat_41    6324
VS_Pat_76    3470
VS_Pat_06    2183
VS_Pat_24    2177
VS_Pat_45    1929
             ...
LM_9            1
LM_13           1
LM_18           1
LM_20           1
LM_25           1
Name: count, Length: 186, dtype: int64

sample_id
Pat_41_Post    5915
Pat_76_Pre     1898
Pat_76_Post    1572
Pat_24_Pre     1492
Pat_06_Pre     1351
               ...
LMSAM_9           1
LMSAM_13          1
LMSAM_18          1
LMSAM_20          1
LMSAM_25          1
Name: count, Length: 218, dtype: int64

HGNC
TTN         262
BRAF        220
MUC16       152
FAT4         66
MUC17        60
           ...
HOXB7         1
TMEM14C       1
PI3KCA        1
EGFR-AS1      1
DUSP4         1
Name: count, Length: 13401, dtype: int64

HGVSp
p.Val600Glu           123
p.Met1?                31
p.Leu20del             17
p.Glu122Lys            15
p.Glu195Lys            15
                     ...
p.Asp869ThrfsTer2       1
p.Arg304ValfsTer6       1
p.Cys999SerfsTer66      1
p.Ser118ArgfsTer97      1
p.Pro47GlnfsTer12       1
Name: count, Length: 26274, dtype: int64

HGVSp_short
p.V600E     123
V600E        62
*3454*       37
p.M1?        31
p.L20del     17
           ...
L328P         1
A2319V        1
P29S          1
N375S         1
E17K          1
Name: count, Length: 27317, dtype: int64

uniprot_id
Q8WZ42    262
P15056    220
Q8WXI7    152
Q6V0I7     66
Q685J3     60
         ...
Q8IZW8      1
P16870      1
P09629      1
Q9P0S9      1
Q13115      1
Name: count, Length: 13188, dtype: int64

consequence
missense_variant                                                                          37045
frameshift_variant                                                                         3938
stop_gained                                                                                2097
inframe_deletion                                                                           1904
missense_variant,splice_region_variant                                                     1047
splice_donor_variant                                                                        537
non_coding_transcript_exon_variant                                                          486
splice_acceptor_variant                                                                     401
intron_variant                                                                              124
inframe_insertion                                                                           113
frameshift_variant,splice_region_variant                                                     93
missense_variant,NMD_transcript_variant                                                      93
upstream_gene_variant                                                                        67
5_prime_UTR_variant                                                                          65
downstream_gene_variant                                                                      55
non_coding_transcript_exon_variant,non_coding_transcript_variant                             49
stop_gained,splice_region_variant                                                            39
splice_region_variant,intron_variant                                                         37
start_lost                                                                                   27
3_prime_UTR_variant                                                                          18
stop_gained,frameshift_variant                                                               16
intron_variant,non_coding_transcript_variant                                                 16
splice_region_variant,non_coding_transcript_exon_variant                                     15
splice_donor_variant,non_coding_transcript_variant                                           14
splice_donor_variant,coding_sequence_variant                                                 14
inframe_deletion,splice_region_variant                                                       12
synonymous_variant                                                                           11
splice_acceptor_variant,coding_sequence_variant                                               9
missense_variant,splice_region_variant,NMD_transcript_variant                                 9
splice_acceptor_variant,intron_variant                                                        7
frameshift_variant,stop_lost                                                                  7
stop_lost                                                                                     7
splice_region_variant,intron_variant,non_coding_transcript_variant                            6
stop_gained,NMD_transcript_variant                                                            5
splice_acceptor_variant,non_coding_transcript_variant                                         5
frameshift_variant,NMD_transcript_variant                                                     5
frameshift_variant,start_lost                                                                 4
stop_gained,inframe_deletion                                                                  4
coding_sequence_variant,5_prime_UTR_variant                                                   4
intron_variant,NMD_transcript_variant                                                         4
splice_donor_variant,intron_variant                                                           4
coding_sequence_variant                                                                       3
splice_region_variant,5_prime_UTR_variant                                                     3
splice_donor_variant,coding_sequence_variant,intron_variant                                   3
3_prime_UTR_variant,NMD_transcript_variant                                                    3
splice_donor_variant,NMD_transcript_variant                                                   2
stop_gained,inframe_insertion,splice_region_variant                                           2
splice_region_variant,non_coding_transcript_exon_variant,non_coding_transcript_variant        2
start_lost,5_prime_UTR_variant                                                                2
frameshift_variant,splice_region_variant,NMD_transcript_variant                               1
synonymous_variant,NMD_transcript_variant                                                     1
start_lost,splice_region_variant                                                              1
start_retained_variant,5_prime_UTR_variant                                                    1
start_lost,inframe_deletion                                                                   1
frameshift_variant,start_lost,start_retained_variant,NMD_transcript_variant                   1
Name: count, dtype: int64

variant_classification
Missense_Mutation         38194
Frame_Shift_Del            3570
Nonsense_Mutation          2163
In_Frame_Del               1916
Splice_Site                 996
RNA                         535
Frame_Shift_Ins             486
Intron                      144
In_Frame_Ins                113
5'Flank                      67
5'UTR                        66
Splice_Region                63
3'Flank                      55
Translation_Start_Site       31
3'UTR                        21
Silent                       12
Nonstop_Mutation              7
IGR                           1
Name: count, dtype: int64

variant_type
SNP    41134
DEL     5676
DNP      950
INS      680
Name: count, dtype: int64

chromosome
1     5254
19    3552
2     3422
7     2960
3     2730
11    2696
12    2507
6     2502
17    2405
5     2290
4     1998
X     1995
16    1894
8     1836
10    1626
9     1500
14    1458
15    1429
20    1253
22    1025
13     827
18     735
21     533
Y       13
Name: count, dtype: int64

start_position
140453136.0    130
141619203.0     13
54011405.0      10
661763.0        10
161044057.0     10
              ...
16895577.0       1
55421128.0       1
16892196.0       1
145281424.0      1
143104714.0      1
Name: count, Length: 38738, dtype: int64

end_position
140453136.0    123
141619203.0     13
140453137.0     11
54011407.0      10
661765.0        10
              ...
16895577.0       1
55421128.0       1
16892196.0       1
145281424.0      1
143104714.0      1
Name: count, Length: 38680, dtype: int64

strand
+    48440
Name: count, dtype: int64

ref_allele
G       20284
C       18662
T        2741
A        2396
-         680
        ...
AGCA        1
GAGT        1
CTGA        1
GCAG        1
CTA         1
Name: count, Length: 157, dtype: int64

tumor_allele_1
G       20284
C       18662
T        2741
A        2396
-         680
        ...
AGCA        1
GAGT        1
CTGA        1
GCAG        1
CTA         1
Name: count, Length: 157, dtype: int64

tumor_allele_2
A               19770
T               17883
-                5676
C                2059
G                1909
                ...
CCTCGC              1
GGCTGTGGCTCC        1
CAGC                1
CTTC                1
CAG                 1
Name: count, Length: 67, dtype: int64

temporality
post treatment    26071
pre treatment     22538
Name: count, dtype: int64

Series([], Name: count, dtype: int64)

source
doi:10.1158/2159-8290.CD-13-0617    47618
doi:10.1200/PO.16.00054               822
doi:10.3390/cancers12082224           122
doi:10.3390/cancers11081203            47
Name: count, dtype: int64

In [142]:
snvs_df.drop(columns=['id', 'creation_datetime', 'HGVSp', 'other_prelevements', 'uniprot_id', 'source'], inplace=True)
snvs_df.isnull().sum()

patientID                   0
sample_id                   0
HGNC                        0
HGVSp_short               193
consequence               170
variant_classification    169
variant_type              169
chromosome                169
start_position            169
end_position              169
strand                    169
ref_allele                169
tumor_allele_1            169
tumor_allele_2            169
temporality                 0
dtype: int64

In [143]:
snvs_df = snvs_df[snvs_df.temporality == 'pre treatment'].reset_index(drop=True)
snvs_df

,patientID,sample_id,HGNC,HGVSp_short,consequence,variant_classification,variant_type,chromosome,start_position,end_position,strand,ref_allele,tumor_allele_1,tumor_allele_2,temporality
0,BS_000,BSAM000,TERT_promoter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
1,BS_000,BSAM000,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
2,BS_001,BSAM001,TERT_promoter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
3,BS_001,BSAM001,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
4,BS_002,BSAM002,TERT_promoter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22533,LM_27,LMSAM_27,DDR2,M441I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
22534,LM_27,LMSAM_27,RAC1,P29S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
22535,LM_27,LMSAM_27,MET,N375S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
22536,LM_27,LMSAM_27,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
22537,LM_27,LMSAM_27,AKT1,E17K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment

In [144]:
gene_list = [
    "BRAF", "RAC1", "STK11", "PIK3CA", "PDGFRA", "ERBB4", "FGFR3", "NRAS", 
    "ALK", "DDR2", "AKT1", "KIT", "JAK2", "MET", "FGFR1", "EGFR", 
    "CDKN2A", "GNA11", "ERBB2", "CTNNB1", "TERT", "FGFR2", "MAP2K1"
]

snvs_df = snvs_df[snvs_df['HGNC'].isin(gene_list)].reset_index(drop=True)
snvs_df

,patientID,sample_id,HGNC,HGVSp_short,consequence,variant_classification,variant_type,chromosome,start_position,end_position,strand,ref_allele,tumor_allele_1,tumor_allele_2,temporality
0,BS_000,BSAM000,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
1,BS_001,BSAM001,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
2,BS_002,BSAM002,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
3,BS_003,BSAM003,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
4,BS_004,BSAM004,BRAF,V600K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,LM_27,LMSAM_27,DDR2,M441I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
320,LM_27,LMSAM_27,RAC1,P29S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
321,LM_27,LMSAM_27,MET,N375S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
322,LM_27,LMSAM_27,BRAF,V600E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment
323,LM_27,LMSAM_27,AKT1,E17K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pre treatment

In [145]:
from sklearn.preprocessing import OneHotEncoder, MultiLabelBinarizer

categorical_cols = ['HGNC', 'HGVSp_short', 'variant_type']

for feat in categorical_cols:
    snvs_df[feat] = snvs_df[feat].fillna('Unknown')

enc = OneHotEncoder(sparse_output=False)

one_hot_encoded = enc.fit_transform(snvs_df[categorical_cols])
one_hot_snvs_df = pd.DataFrame(one_hot_encoded, columns=enc.get_feature_names_out(categorical_cols))

snvs_df_encoded = pd.concat([snvs_df['patientID'], one_hot_snvs_df], axis=1)
# display(snvs_df_encoded)


snvs_df['consequence_list'] = snvs_df['consequence'].fillna('Unknown').str.split(',')

mlb = MultiLabelBinarizer()
enc_arr = mlb.fit_transform(snvs_df['consequence_list']) 

snvs_df_mlb = pd.DataFrame(enc_arr, columns=['cons_' + name for name in mlb.classes_])

snvs_df_encoded = pd.concat([snvs_df_encoded, snvs_df_mlb], axis=1)
snvs_df_encoded

,patientID,HGNC_AKT1,HGNC_ALK,HGNC_BRAF,HGNC_CDKN2A,HGNC_CTNNB1,HGNC_DDR2,HGNC_EGFR,HGNC_ERBB2,HGNC_ERBB4,...,variant_type_Unknown,cons_Unknown,cons_frameshift_variant,cons_inframe_deletion,cons_missense_variant,cons_splice_acceptor_variant,cons_splice_donor_variant,cons_splice_region_variant,cons_stop_gained,cons_upstream_gene_variant
0,BS_000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
1,BS_001,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
2,BS_002,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
3,BS_003,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
4,BS_004,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,LM_27,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
320,LM_27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
321,LM_27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
322,LM_27,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
323,LM_27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0

In [146]:
snvs_df_encoded = snvs_df_encoded.groupby(['patientID']).max().reset_index()
snvs_df_encoded

,patientID,HGNC_AKT1,HGNC_ALK,HGNC_BRAF,HGNC_CDKN2A,HGNC_CTNNB1,HGNC_DDR2,HGNC_EGFR,HGNC_ERBB2,HGNC_ERBB4,...,variant_type_Unknown,cons_Unknown,cons_frameshift_variant,cons_inframe_deletion,cons_missense_variant,cons_splice_acceptor_variant,cons_splice_donor_variant,cons_splice_region_variant,cons_stop_gained,cons_upstream_gene_variant
0,BS_000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
1,BS_001,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
2,BS_002,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
3,BS_003,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
4,BS_004,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,VS_Pat_66,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0,0,0,1,0,0,0,0,0
173,VS_Pat_70,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,1,0
174,VS_Pat_73,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,0,0,0
175,VS_Pat_74,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0,0,1,1,0,0,0,0,0
176,VS_Pat_76,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,0,0,1,0,0,1,0,0

## Merge clinical+snvs

In [147]:
clinical_snvs_df = clinical_df.merge(snvs_df_encoded, how='left', on='patientID')
clinical_snvs_df

,patientID,sex,age,LDH,PFS_status,PFS_month,drug,BOR,BRAF_mut,pre_MAPKi_treatment,...,variant_type_Unknown,cons_Unknown,cons_frameshift_variant,cons_inframe_deletion,cons_missense_variant,cons_splice_acceptor_variant,cons_splice_donor_variant,cons_splice_region_variant,cons_stop_gained,cons_upstream_gene_variant
0,BS_000,male,56,normal,1.0,30.5,dabrafenib + trametinib,PD,V600E,no,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BS_001,male,86,normal,0.0,24.1,dabrafenib,SD,V600E,no,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BS_002,female,47,normal,0.0,14.1,dabrafenib + trametinib,CR,V600E,no,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BS_003,female,50,NaN,1.0,1.6,vemurafenib,PD,V600E,no,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,BS_004,female,47,elevated,1.0,11.9,dabrafenib + trametinib,PD,V600K,no,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,HL_40,male,47,NaN,1.0,3.0,vemurafenib,PR,V600E,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
413,HL_41,male,39,NaN,1.0,4.0,vemurafenib,PR,V600E,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,HL_42,male,84,NaN,1.0,8.0,dabrafenib,PR,V600E,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,HL_43,female,41,NaN,1.0,10.9,vemurafenib,PR,V600E,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,HL_44,male,83,NaN,1.0,4.4,vemurafenib,SD,V600K,no,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [148]:
count_unique_value_per_class(clinical_snvs_df)

patientID
BS_000    1
BS_001    1
BS_002    1
BS_003    1
BS_004    1
         ..
HL_40     1
HL_41     1
HL_42     1
HL_43     1
HL_44     1
Name: count, Length: 417, dtype: int64

sex
male      243
female    174
Name: count, dtype: int64

age
51    15
62    15
55    14
47    13
43    12
      ..
91     1
18     1
94     1
27     1
37     1
Name: count, Length: 72, dtype: int64

LDH
normal      159
elevated    115
Name: count, dtype: int64

PFS_status
1.0    341
0.0     74
Name: count, dtype: int64

PFS_month
1.9     16
1.4     13
2.8      9
1.8      9
3.7      9
        ..
5.0      1
10.8     1
12.4     1
9.7      1
5.3      1
Name: count, Length: 157, dtype: int64

drug
vemurafenib                  204
dabrafenib + trametinib       95
vemurafenib + cobimetinib     69
dabrafenib                    48
Name: count, dtype: int64

BOR
PD    141
PR    135
CR     79
SD     55
Name: count, dtype: int64

BRAF_mut
V600E                  340
V600K                   54
MND                     19
V600R                    2
V600E; R558Q             1
V600E; K601I; C195W      1
Name: count, dtype: int64

pre_MAPKi_treatment
no                                     393
Chemotherapy                            11
IL-2 (High-dose IL-2)                    4
yes                                      4
MK-3475                                  2
Ipi (ipilimumab(adjuvant trial))         2
IFN (interferon (adjuvant setting))      1
Name: count, dtype: int64

HGNC_AKT1
0.0    171
1.0      6
Name: count, dtype: int64

HGNC_ALK
0.0    170
1.0      7
Name: count, dtype: int64

HGNC_BRAF
1.0    175
0.0      2
Name: count, dtype: int64

HGNC_CDKN2A
0.0    150
1.0     27
Name: count, dtype: int64

HGNC_CTNNB1
0.0    168
1.0      9
Name: count, dtype: int64

HGNC_DDR2
0.0    174
1.0      3
Name: count, dtype: int64

HGNC_EGFR
0.0    172
1.0      5
Name: count, dtype: int64

HGNC_ERBB2
0.0    173
1.0      4
Name: count, dtype: int64

HGNC_ERBB4
0.0    166
1.0     11
Name: count, dtype: int64

HGNC_FGFR1
0.0    176
1.0      1
Name: count, dtype: int64

HGNC_FGFR2
0.0    172
1.0      5
Name: count, dtype: int64

HGNC_FGFR3
0.0    174
1.0      3
Name: count, dtype: int64

HGNC_GNA11
0.0    176
1.0      1
Name: count, dtype: int64

HGNC_JAK2
0.0    175
1.0      2
Name: count, dtype: int64

HGNC_KIT
0.0    174
1.0      3
Name: count, dtype: int64

HGNC_MAP2K1
0.0    167
1.0     10
Name: count, dtype: int64

HGNC_MET
0.0    165
1.0     12
Name: count, dtype: int64

HGNC_NRAS
0.0    174
1.0      3
Name: count, dtype: int64

HGNC_PDGFRA
0.0    174
1.0      3
Name: count, dtype: int64

HGNC_PIK3CA
0.0    170
1.0      7
Name: count, dtype: int64

HGNC_RAC1
0.0    170
1.0      7
Name: count, dtype: int64

HGNC_STK11
0.0    176
1.0      1
Name: count, dtype: int64

HGNC_TERT
0.0    167
1.0     10
Name: count, dtype: int64

HGVSp_short_D46E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_E17K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_G302D
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_I155M
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_M441I
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_N375S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_P124L
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_P29S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_P4L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_S45del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_S45del3
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_Unknown
0.0    154
1.0     23
Name: count, dtype: int64

HGVSp_short_V600E
0.0    115
1.0     62
Name: count, dtype: int64

HGVSp_short_V600K
0.0    165
1.0     12
Name: count, dtype: int64

HGVSp_short_V600R
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.A148Gfs*45
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.A324T
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.A600T
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.A647Hfs*64
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.C195W
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.C801Lfs*9
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.D153Tfs*14
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.D190N
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.D484N
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.D776N
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.D810N
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E117del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E268D
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E441del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E545K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E612D
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E695K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E85K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.E872K
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_p.E88*
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_p.F53Y
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G101W
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G195V
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G222S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G276W
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G340R
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G346E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G34E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G38_A39del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G445E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G645R
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G691M
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G709E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G930E
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.G963S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.H1047R
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.H83Y
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.I393N
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.K601I
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L1302F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L185F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L312F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L380F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L487V
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.L540F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.M52Tfs*62
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.N454_L455delinsKF
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.N537S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P114L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P124L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P124S
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_p.P195L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P294L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P29S
0.0    174
1.0      3
Name: count, dtype: int64

HGVSp_short_p.P331K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P367S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P38S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P534L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P619L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P708S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P75S
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P911L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P925L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.P999L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.Q56P
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.Q61K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R106C
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R1170*
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R251Q
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R535C
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R557C
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R558Q
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R58*
0.0    171
1.0      6
Name: count, dtype: int64

HGVSp_short_p.R606K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R774Q
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R80*
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_p.R832*
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.R860K
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S440F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S45F
0.0    175
1.0      2
Name: count, dtype: int64

HGVSp_short_p.S45del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S467F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S467L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S670L
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S77F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.S967F
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.T115A
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.T41_S45del
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.V344G
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.V424I
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.V600E
1.0    93
0.0    84
Name: count, dtype: int64

HGVSp_short_p.V600K
0.0    169
1.0      8
Name: count, dtype: int64

HGVSp_short_p.W15*
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.X1312_splice
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.X51_splice
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.X544_splice
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.Y229C
0.0    176
1.0      1
Name: count, dtype: int64

HGVSp_short_p.Y679F
0.0    176
1.0      1
Name: count, dtype: int64

variant_type_DEL
0.0    168
1.0      9
Name: count, dtype: int64

variant_type_DNP
0.0    160
1.0     17
Name: count, dtype: int64

variant_type_SNP
1.0    98
0.0    79
Name: count, dtype: int64

variant_type_Unknown
0.0    103
1.0     74
Name: count, dtype: int64

cons_Unknown
0.0    103
1.0     74
Name: count, dtype: int64

cons_frameshift_variant
0.0    172
1.0      5
Name: count, dtype: int64

cons_inframe_deletion
0.0    172
1.0      5
Name: count, dtype: int64

cons_missense_variant
1.0    102
0.0     75
Name: count, dtype: int64

cons_splice_acceptor_variant
0.0    175
1.0      2
Name: count, dtype: int64

cons_splice_donor_variant
0.0    176
1.0      1
Name: count, dtype: int64

cons_splice_region_variant
0.0    172
1.0      5
Name: count, dtype: int64

cons_stop_gained
0.0    165
1.0     12
Name: count, dtype: int64

cons_upstream_gene_variant
0.0    170
1.0      7
Name: count, dtype: int64

In [149]:
clinical_snvs_df.isnull().sum()

patientID                         0
sex                               0
age                               0
LDH                             143
PFS_status                        2
                               ...
cons_splice_acceptor_variant    240
cons_splice_donor_variant       240
cons_splice_region_variant      240
cons_stop_gained                240
cons_upstream_gene_variant      240
Length: 159, dtype: int64